# åˆ›å»ºè€…ï¼šç”¨æˆ·è‡ªå®šä¹‰èŠ‚ç‚¹é…ç½®
# åˆ›å»ºæ—¶é—´ï¼š2025-09-27 08:00:00

# å•èŠ‚ç‚¹é…ç½®
proxies:
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½
    server: 116.49.237.130
    port: 2673
    password: BxceQaOe
    network: tcp
    sni: t.me/ripaojiedian
    skip-cert-verify: true
  - type: vmess
    name: ğŸ‡­ğŸ‡°HKÂ²_3|1.2MB/s|2%|GPT|YT|X
    server: hkt.gotochinatown.net
    port: 80
    uuid: 21747146-3507-11ed-bb74-f23c9164ca5d
    alterId: 2
    network: ws
    cipher: auto
    servername: hkt.gotochinatown.net
    ws-opts:
      path: /
      headers:
        Host: hkt.gotochinatown.net
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_1
    server: 58.152.26.173
    port: 443
    password: BxceQaOe
    network: tcp
    sni: t.me/ripaojiedian
    skip-cert-verify: true
  - type: ss
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_2
    server: slur.izenny.com
    port: 40063
    cipher: chacha20-ietf-poly1305
    password: db8a0e6b-5fd7-435d-9558-5c86b0679c4d
  - type: ss
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_3
    server: slur.izenny.com
    port: 55407
    cipher: chacha20-ietf-poly1305
    password: d9b85218-da37-42a7-8906-67bab810252c
  - type: ss
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_4
    server: slur.izenny.com
    port: 48907
    cipher: chacha20-ietf-poly1305
    password: db8a0e6b-5fd7-435d-9558-5c86b0679c4d
  - type: ss
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_5
    server: slur.izenny.com
    port: 32009
    cipher: chacha20-ietf-poly1305
    password: d9b85218-da37-42a7-8906-67bab810252c
  - type: trojan
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½
    server: usygh.zippydeal.xyz
    port: 5710
    password: fg20mtCFHy
    network: tcp
    sni: usygh.zippydeal.xyz
    skip-cert-verify: true
  - type: ss
    name: ğŸ‡°ğŸ‡·_KR_éŸ©å›½
    server: 54.180.234.116
    port: 80
    cipher: aes-256-gcm
    password: dada0801
  - type: vless
    name: ğŸ‡©ğŸ‡ª_DE_å¾·å›½
    server: 78.47.80.152
    port: 443
    uuid: Warpi-Free-Vpn-In-GooglePlay
    network: tcp
    encryption: none
  - type: ss
    name: ğŸ‡¦ğŸ‡º_AU_æ¾³å¤§åˆ©äºš
    server: 185.234.145.250
    port: 8443
    cipher: chacha20-ietf-poly1305
    password: AA51kVovHrYCEFntBjOFfP
  - type: vless
    name: ğŸ‡·ğŸ‡º_RU_ä¿„ç½—æ–¯
    server: 81.161.98.228
    port: 1443
    uuid: 00f02ab2-6f2d-449f-a089-d182a2fac59a
    network: ws
    servername: cdn.filterai.ru
    tls: true
    ws-opts:
      path: /websocketpl
      headers:
        Host: cdn.filterai.ru
    client-fingerprint: chrome
  - type: ss
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_6
    server: slur.izenny.com
    port: 57577
    cipher: chacha20-ietf-poly1305
    password: db8a0e6b-5fd7-435d-9558-5c86b0679c4d
  - type: trojan
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_1
    server: 38.180.72.162
    port: 2053
    password: eb7339c5-70e4-4c7b-b5ef-4128adc8136a
    network: ws
    sni: joss.gpj1.web.id
    fingerprint: randomized
    tls: true
    ws-opts:
      path: /Free-VPN-CF-Geo-Project/38.180.72.162=2053
      headers:
        Host: joss.gpj1.web.id
  - type: ss
    name: ğŸ‡ºğŸ‡¦_UA_ä¹Œå…‹å…°
    server: 213.111.132.46
    port: 8443
    cipher: chacha20-ietf-poly1305
    password: VIxmBLIylEewLSsAOpChqn
  - type: ss
    name: ğŸ‡°ğŸ‡·_KR_éŸ©å›½_1
    server: 13.124.194.133
    port: 80
    cipher: aes-256-gcm
    password: dada0801
  - type: vless
    name: ğŸ‡·ğŸ‡º_RU_ä¿„ç½—æ–¯_1
    server: 178.130.43.35
    port: 443
    uuid: id8567660651
    network: tcp
    servername: ozon.ru
    tls: true
    encryption: none
    reality-opts:
      public-key: 0IGwg1a5Gz3UdIbftPAkdWM6Qwy5EeoHEKqzx7GA_kQ
      short-id: "8643"
      spider-x: /11i8kFFdlH5ahmL
    client-fingerprint: chrome
    flow: xtls-rprx-vision
  - type: trojan
    name: ğŸ‡¨ğŸ‡­_CH_ç‘å£«
    server: 138.124.30.8
    port: 443
    password: 0311306e-56d4-4aa1-bde5-8cede7fcd3e4
    network: ws
    sni: joss.gpj1.web.id
    fingerprint: randomized
    tls: true
    ws-opts:
      path: /Free-VPN-CF-Geo-Project/138.124.30.8=443
      headers:
        Host: joss.gpj1.web.id
  - type: ss
    name: ğŸ‡®ğŸ‡ª_IE_çˆ±å°”å…°
    server: 3.254.86.168
    port: 443
    cipher: aes-256-cfb
    password: amazonskr05
  - type: vless
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_7
    server: 62.60.148.21
    port: 443
    uuid: 39e5cc2f-1294-4a42-bb58-306a8be785e1
    network: tcp
    servername: st.ozone.ru
    tls: true
    encryption: none
    reality-opts:
      public-key: BkAG_uWeUj7BCHqYjrz1JyH0TMvO_KywubV7WJN17ho
      short-id: ee6f3e8f44b1f0b6
    client-fingerprint: chrome
    flow: xtls-rprx-vision
  - type: vless
    name: ğŸ‡·ğŸ‡º_RU_ä¿„ç½—æ–¯_2
    server: 178.236.244.22
    port: 443
    uuid: cf97c9a9-441e-43e1-9bd2-f66a198cd87b
    network: tcp
    servername: kinopoisk.ru
    tls: true
    encryption: none
    reality-opts:
      public-key: 3LwULpxLmY98y-IDJAeOwZzlVo5s5BnzKz4D5A7lQn4
      short-id: 586207ca3cf8d389
    client-fingerprint: chrome
    flow: xtls-rprx-vision
  - type: vless
    name: ğŸ‡¸ğŸ‡¦_SA_æ²™ç‰¹é˜¿æ‹‰ä¼¯
    server: 77.110.101.240
    port: 443
    uuid: cf97c9a9-441e-43e1-9bd2-f66a198cd87b
    network: tcp
    servername: kinopoisk.ru
    tls: true
    encryption: none
    reality-opts:
      public-key: 4Y3V5AIralE3HIAYXCe3beUGsUiBei0mCmbhPXGAgHg
      short-id: 2fc1abafec7cb87b
    client-fingerprint: chrome
    flow: xtls-rprx-vision
  - type: hysteria2
    name: ğŸ‡¬ğŸ‡§_GB_è‹±å›½
    server: 154.16.183.27
    port: 30102
    password: 338ce171-d764-4610-8fd5-6688b0d321f0
    skip-cert-verify: true
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_2
    server: 144.31.27.190
    port: 443
    uuid: cf97c9a9-441e-43e1-9bd2-f66a198cd87b
    network: tcp
    servername: eh.vk.com
    tls: true
    encryption: none
    reality-opts:
      public-key: qKDDfmvDvBgtUqhSnJf8OFDCaBPZ1Mr0GKGZyATtggo
      short-id: a20d3ed244c76426
    client-fingerprint: chrome
    flow: xtls-rprx-vision
  - type: vless
    name: ğŸ‡¸ğŸ‡¦_SA_æ²™ç‰¹é˜¿æ‹‰ä¼¯1
    server: usa1.tunnelx.space
    port: 2087
    uuid: 393040206-client-475
    network: ws
    servername: ws.usa1.tunnelx.space
    encryption: none
    ws-opts:
      path: /assets/img/banner_v3.webp/#@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL
      headers:
        Host: ws.usa1.tunnelx.space
