# åˆ›å»ºè€…ï¼šç”¨æˆ·è‡ªå®šä¹‰èŠ‚ç‚¹é…ç½®
# åˆ›å»ºæ—¶é—´ï¼š2025-09-27 08:00:00

# å•èŠ‚ç‚¹é…ç½®
proxies:
  - type: vmess
    name: ğŸ‡ºğŸ‡¸ US_156
    server: aflzzul.meiquankongjian.com
    port: 52511
    uuid: 342bacfd-2b8f-3f49-a16e-439db5b0b9d5
    alterId: 0
    network: ws
    cipher: auto
    servername: aflzzul.meiquankongjian.com
    ws-opts:
      path: /564dfa20/
      headers:
        Host: aflzzul.meiquankongjian.com
  - type: vmess
    name: ğŸ‡°ğŸ‡·KR-125.134.123.178-1122
    server: 125.134.123.178
    port: 50001
    uuid: ffde381b-4a30-41d4-90eb-151f228b06ea
    alterId: 0
    network: ws
    cipher: auto
    servername: aa.nbee.pp.ua
    ws-opts:
      path: /qq
      headers:
        Host: aa.nbee.pp.ua
    tls: true
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½
    server: 219.79.165.55
    port: 443
    password: BxceQaOe
    network: tcp
    sni: t.me/ripaojiedian
    skip-cert-verify: true
  - type: trojan
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½
    server: 69.84.182.18
    port: 8443
    password: 559b90ec-b620-4255-80a5-c64b8d3ffe6c
    network: ws
    sni: cdn-node-oss-64.paofu.de
    ws-opts:
      path: /profile/sharenode
      headers:
        Host: cdn-node-oss-64.paofu.de
  - type: trojan
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_1
    server: 107.174.82.102.sslip.io
    port: 443
    password: bb824a22-b7ce-427b-9ed6-1adf0751da02
    network: ws
    sni: 107.174.82.102.sslip.io
    alpn:
      - http/1.1
    fingerprint: chrome
    tls: true
    ws-opts:
      path: /gXKGj8a1tp1nNbZEcRugowKV
      headers:
        Host: 107.174.82.102.sslip.io
  - type: vless
    name: ğŸ‡©ğŸ‡ª_DE_å¾·å›½
    server: beast-masters.fonixapp.org
    port: 28924
    uuid: 2f79c61d-043b-421f-860e-4924246609e1
    network: tcp
    servername: expedia.com
    tls: true
    encryption: none
    reality-opts:
      public-key: 4Qz4G28t9qnfp9i8prlehAmCaqI7w56OKuHgpfytXH8
      short-id: 5ff1a443
    client-fingerprint: chrome
    flow: xtls-rprx-vision
  - type: vmess
    name: ğŸ‡³ğŸ‡± ITÂ²_1|1.6MB/s|TK-NL|X|KeepHistory
    server: v5.heduian.link
    port: 30805
    uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
    alterId: 2
    network: tcp
    cipher: auto
    servername: v5.heduian.link
  - type: trojan
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_2
    server: ip.sb
    port: 8443
    password: trojan
    network: ws
    sni: fofang.pages.dev
    tls: true
    ws-opts:
      path: /
  - type: ss
    name: ğŸ‡®ğŸ‡·_IR_ä¼Šæœ—
    server: 151.242.251.137
    port: 8080
    cipher: chacha20-ietf-poly1305
    password: o5osZg269v5zHpYjr1xY9s
  - type: hysteria2
    name: ğŸ‡®ğŸ‡·_IR_ä¼Šæœ—_1
    server: tr.xn--9kqx4sc0n.shop
    port: 21324
    password: 05d0e442-5d3d-4fa7-a21f-b1bfa82e46cc
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_3
    server: ip.sb
    port: 443
    uuid: b15acbbd-a093-4269-a20d-d74dce4bff89
    network: ws
    servername: 1079ca08.turk-71y.pages.dev
    tls: true
    ws-opts:
      path: /rqi2wmvf7pii4hrp/njiumy4xmi4xodu=?ed=2560
      headers:
        Host: 1079ca08.turk-71y.pages.dev
    client-fingerprint: chrome
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_4
    server: antimage.fonixapp.org
    port: 29000
    uuid: 58a3efa1-94a6-4e03-b5b7-c4a398585979
    network: tcp
    servername: deepl.com
    tls: true
    encryption: none
    reality-opts:
      public-key: lbo1jWRdkDrMcBkRcVXUBGoEbOun23CERmtkOWDS7Go
      short-id: a941df4328
    client-fingerprint: chrome
    flow: xtls-rprx-vision
  - type: vmess
    name: ã€æœºåœºæ¨èï¼šhttps://a0a.xyz/ã€‘7
    server: 172.82.67.156.sslip.io
    port: 443
    uuid: 55821780-6970-49df-8a23-800c2c9b7d3a
    alterId: 0
    network: ws
    cipher: auto
    servername: 172.82.67.156.sslip.io
    ws-opts:
      path: /SGBvMNdpPtNtvgyaVXm
      headers:
        Host: 172.82.67.156.sslip.io
    tls: true
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_5
    server: silverzebra.fonixapp.org
    port: 31502
    uuid: b20c12e7-f071-4829-94e7-17dc4e43a37a
    network: tcp
    servername: marmiton.org
    tls: true
    encryption: none
    reality-opts:
      public-key: oenAlMhG602prGwOqnAt5yZ55yuDEfZwGZXn-WaxizM
      short-id: e1814a
      spider-x: /
    client-fingerprint: chrome
    flow: xtls-rprx-vision
  - type: hysteria2
    name: ğŸ‡®ğŸ‡·_IR_ä¼Šæœ—_2
    server: tr.xn--9kqx4sc0n.shop
    port: 21967
    password: 05d0e442-5d3d-4fa7-a21f-b1bfa82e46cc
  - type: hysteria2
    name: ğŸ‡¨ğŸ‡¦_CA_åŠ æ‹¿å¤§
    server: 140.238.137.165
    port: 30102
    password: 338ce171-d764-4610-8fd5-6688b0d321f0
    skip-cert-verify: true
    sni: du.wish.ml
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_6
    server: ger.americanexpressbanks.com
    port: 443
    uuid: 6405f134-503f-40b3-aea9-cc92fa77b5ac
    network: ws
    servername: ger.americanexpressbanks.com
    tls: true
    ws-opts:
      path: /xYzAbc123
      headers:
        Host: ger.americanexpressbanks.com
    client-fingerprint: chrome
    alpn:
      - h3
      - h2
      - http/1.1
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_7
    server: drow-ranger.fonixapp.org
    port: 27994
    uuid: 119b539d-e4ac-464d-a389-ace2e388b805
    network: tcp
    servername: ilovepdf.com
    tls: true
    encryption: none
    reality-opts:
      public-key: lPSI3kHNhurG5ak6LTNc6NAJmSOvdt8EWjLHdsJXLCE
      short-id: f2951ff6a7
    client-fingerprint: chrome
    flow: xtls-rprx-vision
  - type: vless
    name: ğŸ‡©ğŸ‡ª_DE_å¾·å›½_1
    server: vp9.myphotomoments.ir
    port: 443
    uuid: Warpi-Free-Vpn-In-GooglePlay
    network: tcp
    encryption: none
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_8
    server: graygoat.fonixapp.org
    port: 12645
    uuid: 8d5bca78-f49f-4e49-ad7b-bb58da44d40b
    network: tcp
    servername: smallpdf.com
    tls: true
    encryption: none
    reality-opts:
      public-key: U15vYKJBiI0x1Sltv3qZrtuRoGlw5fIu-jlHfN1hBB4
      short-id: 3fd623
    client-fingerprint: chrome
    flow: xtls-rprx-vision
  - type: hysteria2
    name: ğŸ‡¸ğŸ‡ª_SE_ç‘å…¸
    server: us.xn--9kqx4sc0n.shop
    port: 21363
    password: 05d0e442-5d3d-4fa7-a21f-b1bfa82e46cc
  - type: vless
    name: ğŸ‡¸ğŸ‡¦_SA_æ²™ç‰¹é˜¿æ‹‰ä¼¯
    server: usa1.tunnelx.space
    port: 2087
    uuid: 393040206-client-475
    network: ws
    servername: ws.usa1.tunnelx.space
    encryption: none
    ws-opts:
      path: /assets/img/banner_v3.webp/#@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL,@V2RAY_SPATIAL
      headers:
        Host: ws.usa1.tunnelx.space
  - type: vless
    name: ğŸ‡®ğŸ‡·_IR_ä¼Šæœ—_3
    server: vp8.myphotomoments.ir
    port: 443
    uuid: Warpi-Free-Vpn-In-GooglePlay
    network: tcp
    encryption: none
  - type: trojan
    name: ğŸ‡©ğŸ‡°_DK_ä¸¹éº¦
    server: 195.85.59.95
    port: 8443
    password: 559b90ec-b620-4255-80a5-c64b8d3ffe6c
    network: ws
    sni: cdn-node-oss-64.paofu.de
    ws-opts:
      path: /profile/sharenode
      headers:
        Host: cdn-node-oss-64.paofu.de
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_9
    server: shadowshaman.fonixapp.org
    port: 26861
    uuid: 04db6938-72dc-42b4-a096-cc6a5e8316d2
    network: tcp
    servername: groww.in
    tls: true
    encryption: none
    reality-opts:
      public-key: IIdE2p3vqHDjHfLrvJXkrLoYpYMJH0R1tacCkHiDtAA
      short-id: ecc1c4
      spider-x: /
    client-fingerprint: chrome
    flow: xtls-rprx-vision
  - type: vless
    name: ğŸ‡©ğŸ‡ª_DE_å¾·å›½_2
    server: vp5.myphotomoments.ir
    port: 443
    uuid: Warpi-Free-Vpn-In-GooglePlay
    network: tcp
    encryption: none
