# åˆ›å»ºè€…ï¼šç”¨æˆ·è‡ªå®šä¹‰èŠ‚ç‚¹é…ç½®
# åˆ›å»ºæ—¶é—´ï¼š2025-09-27 08:00:00

# å•èŠ‚ç‚¹é…ç½®
proxies:
  - type: vmess
    name: è§£é”å¥ˆé£/TikTok/ChatGPT
    server: n1744453320.lie5d.cyou
    port: 443
    uuid: 8889a08a-09f8-4c97-bed2-df31b62fcf23
    alterId: 0
    network: ws
    cipher: auto
    servername: n1744453320.lie5d.cyou
    ws-opts:
      path: /
      headers:
        Host: n1744453320.lie5d.cyou
    tls: true
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½
    server: 36.150.215.147
    port: 4666
    password: BxceQaOe
    network: tcp
    sni: t.me/ripaojiedian
    skip-cert-verify: true
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½
    server: 1760516058.tencentapp.cn
    port: 443
    uuid: 6911bb2c-a220-45a6-94fb-1ea8d9a1e94e
    network: ws
    servername: stall3.sni2026.netlib.re
    tls: true
    encryption: none
    ws-opts:
      path: /proxyip=tw.soso.edu.kg:43
      headers:
        Host: stall3.sni2026.netlib.re
    client-fingerprint: random
    alpn:
      - h3
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_1
    server: 38.47.122.75
    port: 30005
    uuid: 6911bb2c-a220-45a6-94fb-1ea8d9a1e94e
    network: ws
    servername: stall3.sni2026.netlib.re
    tls: true
    encryption: none
    ws-opts:
      path: /proxyip=tw.soso.edu.kg:43
      headers:
        Host: stall3.sni2026.netlib.re
    client-fingerprint: random
    alpn:
      - h3
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_1
    server: 36.150.215.246
    port: 5156
    password: BxceQaOe
    network: tcp
    sni: t.me/ripaojiedian
    skip-cert-verify: true
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_2
    server: 8.35.211.250
    port: 2083
    uuid: 6911bb2c-a220-45a6-94fb-1ea8d9a1e94e
    network: ws
    servername: stall3.sni2026.netlib.re
    tls: true
    encryption: none
    ws-opts:
      path: /proxyip=tw.soso.edu.kg:43
      headers:
        Host: stall3.sni2026.netlib.re
    client-fingerprint: random
    alpn:
      - h3
  - type: vless
    name: ğŸ‡²ğŸ‡©_MD_æ‘©å°”å¤šç“¦
    server: pq.vmjp3.yydjc.top
    port: 443
    uuid: de81cf6b-0d2f-42be-ac60-a3b734216739
    network: tcp
    servername: iosapps.itunes.apple.com
    tls: true
    reality-opts:
      public-key: pR8CV43xvSgvzSXPVLCVomjw-yZvNyqU32kietO2pEc
      short-id: a6115a2c
    client-fingerprint: ios
    flow: xtls-rprx-vision
  - type: vmess
    name: ğŸ‡ºğŸ‡¸USÂ²_1|5.1MB/s|47%|GPTâº|YT-CN|TK|NF|X
    server: yg1.ygkkk.dpdns.org
    port: 443
    uuid: c934d81c-bacb-4ff2-8780-da9668cd0fba
    alterId: 0
    network: ws
    cipher: auto
    servername: rn1.alwaysme.ggff.net
    ws-opts:
      path: /c934d81c-bacb-4ff2-8780-da9668cd0fba-vm?ed=2048
      headers:
        Host: rn1.alwaysme.ggff.net
    tls: true
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_3
    server: 172.64.144.19
    port: 443
    uuid: db2c8a95-f751-46e3-b05e-d2def66850fb
    network: ws
    servername: ayanamirei.11160321.xyz
    tls: true
    ws-opts:
      path: /socks5://test123:test123@122.10.144.6:1080/
      headers:
        Host: ayanamirei.11160321.xyz
    client-fingerprint: randomized
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_4
    server: 23.185.168.144
    port: 8602
    uuid: 6911bb2c-a220-45a6-94fb-1ea8d9a1e94e
    network: ws
    servername: stall3.sni2026.netlib.re
    tls: true
    encryption: none
    ws-opts:
      path: /proxyip=tw.soso.edu.kg:43
      headers:
        Host: stall3.sni2026.netlib.re
    client-fingerprint: random
    alpn:
      - h3
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_5
    server: 172.66.156.81
    port: 80
    uuid: 91aa6fff-ef91-4f7b-9aac-e3b7cac44c83
    network: ws
    servername: websocket.network.www.speedtest.net.flutter.dev.russia.pyt.digitalcity5.xyz.
    encryption: none
    ws-opts:
      path: /@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy
      headers:
        Host: websocket.network.www.speedtest.net.flutter.dev.russia.pyt.digitalcity5.xyz.
  - type: hysteria2
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_6
    server: cc65f71a-t4v9c0-t5waci-4550.la.shifen.uk
    port: 1743
    password: 6286105c-fb6d-11ef-be96-f23c93136cb3
    sni: cc65f71a-t4v9c0-t5waci-4550.la.shifen.uk
  - type: hysteria2
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_7
    server: 70555517-t3bpc0-t9lxaa-1glq.la.shifen.uk
    port: 1743
    password: df7bed3c-06eb-11f0-8ebc-f23c93141fad
    sni: 70555517-t3bpc0-t9lxaa-1glq.la.shifen.uk
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_8
    server: 172.67.133.33
    port: 8443
    uuid: e0976e35-a651-4f34-b5b1-c9ac9f75cb74
    network: ws
    servername: private.besttotaldns.com
    tls: true
    encryption: none
    ws-opts:
      path: /J5aKLOY1R7ONXYCM
      headers:
        Host: private.besttotaldns.com
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_9
    server: 69.84.182.108
    port: 443
    uuid: de81cf6b-0d2f-42be-ac60-a3b734216739
    network: ws
    servername: pq-us4.globals-download.com
    tls: true
    ws-opts:
      path: /pq/us4
      headers:
        Host: pq-us4.globals-download.com
    client-fingerprint: chrome
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_10
    server: uuk2v.tok8888.com
    port: 8443
    uuid: 9132154a-95b8-4627-9363-9d078f1dbcfe
    network: tcp
    servername: businessmadesimple.com
    tls: true
    reality-opts:
      public-key: GcOtIhZbkznrBYohK7rvjV0oVoQvC4y38VIExs6KUwA
    client-fingerprint: ios
    flow: xtls-rprx-vision
  - type: hysteria2
    name: ğŸ‡·ğŸ‡º_RU_ä¿„ç½—æ–¯
    server: ny.jueduibupao.top
    port: 50001
    password: f051d9ed-f74d-4438-b368-033d80f6ae45
    skip-cert-verify: true
    sni: ny.jueduibupao.top
