# åˆ›å»ºè€…ï¼šç”¨æˆ·è‡ªå®šä¹‰èŠ‚ç‚¹é…ç½®
# åˆ›å»ºæ—¶é—´ï¼š2025-09-27 08:00:00

# å•èŠ‚ç‚¹é…ç½®
proxies:
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½
    server: 116.49.237.130
    port: 518
    password: BxceQaOe
    network: tcp
    sni: t.me/ripaojiedian
    skip-cert-verify: true
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_1
    server: 36.150.215.246
    port: 4011
    password: BxceQaOe
    network: tcp
    sni: t.me/ripaojiedian
    skip-cert-verify: true
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_2
    server: 116.49.237.130
    port: 2173
    password: BxceQaOe
    network: tcp
    sni: t.me/ripaojiedian
    skip-cert-verify: true
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_3
    server: 219.77.239.35
    port: 443
    password: BxceQaOe
    network: tcp
    sni: t.me/ripaojiedian
    skip-cert-verify: true
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½
    server: 152.53.84.101
    port: 20579
    uuid: 93cd7e0f-8a81-4076-be8b-6d3bf3f8f810
    network: tcp
    servername: ilovepdf.com
    tls: true
    encryption: none
    reality-opts:
      public-key: mT6lh-gtbEuWk3Zk6XGF_hYvpLwxTyvwtH7F-_fRbxI
      short-id: 89f1da93
    client-fingerprint: chrome
    flow: xtls-rprx-vision
  - type: vless
    name: ğŸ‡¸ğŸ‡¦_SA_æ²™ç‰¹é˜¿æ‹‰ä¼¯
    server: 77.110.119.225
    port: 443
    uuid: 4819860c-0e62-4804-9c59-967e5c2bed7a
    network: tcp
    servername: st.ozone.ru
    tls: true
    reality-opts:
      public-key: hnec5SxCD6Os-u0FNi_YS5CML1a_oWb0niZJ1mGuFBo
      short-id: 07e904766d29b958
    client-fingerprint: chrome
    flow: xtls-rprx-vision
  - type: vless
    name: ğŸ‡·ğŸ‡´_RO_ç½—é©¬å°¼äºš
    server: zeusolympus.fonixapp.org
    port: 45714
    uuid: 00077dbc-4430-4c2d-baa7-878720254c97
    network: tcp
    servername: ilovepdf.com
    tls: true
    encryption: none
    reality-opts:
      public-key: 0GENC9ZpilKBLqipubONSKa0QjIDIYkrILHExjfy91Q
      short-id: 54387a
      spider-x: /
    client-fingerprint: firefox
    flow: xtls-rprx-vision
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_1
    server: graygoat.fonixapp.org
    port: 48983
    uuid: 75c18b2c-9f28-44e5-9fde-02c00b6d30a0
    network: tcp
    servername: smallpdf.com
    tls: true
    encryption: none
    reality-opts:
      public-key: 7hoSQsWXvX5kVe1gUt5mLIpbfiIp3017V3S6Ym0hqW0
      short-id: 509af44ce1
      spider-x: /
    client-fingerprint: firefox
    flow: xtls-rprx-vision
  - type: trojan
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_2
    server: ip.sb
    port: 8443
    password: trojan
    network: ws
    sni: fofang.pages.dev
    tls: true
    ws-opts:
      path: /
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_3
    server: 172.67.185.98
    port: 8443
    uuid: 635dfb8e-3d28-40c2-bd27-9b85e7bc6bb6
    network: ws
    servername: ion.api-music-fa.com
    tls: true
    ws-opts:
      path: /J5aKLOY1R9ONWYCM
      headers:
        Host: ion.api-music-fa.com
    client-fingerprint: chrome
  - type: trojan
    name: ğŸ‡·ğŸ‡º_RU_ä¿„ç½—æ–¯
    server: 77.221.141.207
    port: 443
    password: edeff73d-065d-4b0a-b848-aad9d3380223
    network: ws
    sni: joss.dus.biz.id
    fingerprint: randomized
    tls: true
    ws-opts:
      path: /Free-VPN-CF-Geo-Project/77.221.141.207=443
      headers:
        Host: joss.dus.biz.id
  - type: hysteria2
    name: ğŸ‡·ğŸ‡º_RU_ä¿„ç½—æ–¯_1
    server: 147.45.49.251
    port: 45183
    password: 4a6bf640-5c5e-41d3-8078-89a12174cf57
    skip-cert-verify: true
    sni: linjp1.jueduibupao.top
  - type: trojan
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_4
    server: 104.25.254.4
    port: 2087
    password: d0298536-d670-4045-bbb1-ddd5ea68683e
    network: ws
    sni: azadnet-bdr.pages.dev
    tls: true
    ws-opts:
      path: /azadnet-bdr.pages.dev/?ed=2560&PROT_TYPE=trojan
      headers:
        Host: azadnet-bdr.pages.dev
  - type: trojan
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_5
    server: kfjdi.pages.dev
    port: 443
    password: er668
    network: ws
    tls: true
    ws-opts:
      path: /
  - type: vless
    name: ğŸ‡­ğŸ‡º_HU_åŒˆç‰™åˆ©
    server: helsinki.fonixapp.org
    port: 54978
    uuid: a79d31ed-99d6-4116-8f50-fa46957ac6a0
    network: tcp
    servername: study.com
    tls: true
    encryption: none
    reality-opts:
      public-key: clfoV7PyfUylden53xvv2FuAoSYFBeZ2JdP0ZzC2ISo
      short-id: cc58ae21d5
      spider-x: /
    client-fingerprint: firefox
    flow: xtls-rprx-vision
  - type: trojan
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_6
    server: 65.109.227.138
    port: 2053
    password: 7d82af32-915f-4619-aa9c-7d3b612d33ff
    network: ws
    sni: joss.dus.biz.id
    fingerprint: randomized
    tls: true
    ws-opts:
      path: /Free-VPN-CF-Geo-Project/65.109.227.138=2053
      headers:
        Host: joss.dus.biz.id
  - type: trojan
    name: ğŸ‡³ğŸ‡±_NL_è·å…°
    server: 86.107.197.239
    port: 443
    password: 5ad5fe82-6b60-4f59-977b-93910ef7a9ca
    network: ws
    sni: joss.dus.biz.id
    tls: true
    ws-opts:
      path: /Free-VPN-CF-Geo-Project/86.107.197.239=443
      headers:
        Host: joss.dus.biz.id
  - type: trojan
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_7
    server: 51.89.128.93
    port: 44004
    password: 6b5b50ff-7798-40dc-9888-b4dd581e5435
    network: ws
    sni: joss.dus.biz.id
    tls: true
    ws-opts:
      path: /Free-VPN-CF-Geo-Project/51.89.128.93=44004
      headers:
        Host: joss.dus.biz.id
