# åˆ›å»ºè€…ï¼šç”¨æˆ·è‡ªå®šä¹‰èŠ‚ç‚¹é…ç½®
# åˆ›å»ºæ—¶é—´ï¼š2025-09-27 08:00:00

# å•èŠ‚ç‚¹é…ç½®
proxies:
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½
    server: oss-cn-shanghai.letssepub.com
    port: 20021
    password: adbac894-90b9-4913-b77e-a715a8d4ebc8
    network: tcp
    sni: dingding-doc.com
    tls: true
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_1
    server: 58.152.53.42
    port: 443
    password: bca467b8c15211d189008a93c7519d3b
    network: tcp
    sni: www.nintendogames.net
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_2
    server: 117.172.176.24
    port: 2283
    password: bca467b8c15211d189008a93c7519d3b
    network: tcp
    sni: www.nintendogames.net
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_3
    server: 36.151.192.242
    port: 4556
    password: BxceQaOe
    network: tcp
    skip-cert-verify: true
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_4
    server: 36.151.192.242
    port: 194
    password: BxceQaOe
    network: tcp
    skip-cert-verify: true
  - type: vmess
    name: å¾·å›½ V2CROSS.COM
    server: 77.37.33.67
    port: 80
    uuid: d967ffca-de90-4daa-bd00-d527e5bae11f
    alterId: 0
    network: ws
    cipher: auto
    servername: google.whatsapp.snapp.torob.basalam.leoshopping77.ir.
    ws-opts:
      path: /?BIA_TELEGRAM(@AZARBAYJAB1)TM(@AZARBAYJAB1)TM(@AZARBAYJAB1)TM(@AZARBAYJAB1)TM(@AZARBAYJAB1)TM(@AZARBAYJAB1)
      headers:
        Host: google.whatsapp.snapp.torob.basalam.leoshopping77.ir.
    tls: true
  - type: vmess
    name: ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹
    server: 104.18.240.238
    port: 80
    uuid: d967ffca-de90-4daa-bd00-d527e5bae11f
    alterId: 0
    network: ws
    cipher: auto
    servername: google.whatsapp.snapp.torob.basalam.leoshopping77.ir.
    ws-opts:
      path: /?BIA_TELEGRAM (@AZARBAYJAB1) TM (@AZARBAYJAB1) TM (@AZARBAYJAB1) TM
        (@AZARBAYJAB1) TM (@AZARBAYJAB1) TM (@AZARBAYJAB1)
      headers:
        Host: google.whatsapp.snapp.torob.basalam.leoshopping77.ir.
    tls: true
  - type: vmess
    name: ğŸ‡ºğŸ‡¸ ç¾å›½ 454
    server: a4932bbe-005c-1509-7b27-51aa7b17a6fb.999161.xyz
    port: 80
    uuid: 34a7da0c-a43a-49b8-a8d0-64b43100090e
    alterId: 0
    network: ws
    cipher: auto
    servername: a4932bbe-005c-1509-7b27-51aa7b17a6fb.999161.xyz
    ws-opts:
      path: /e7JS5ETJeA85VyjPCYXwETL
      headers:
        Host: a4932bbe-005c-1509-7b27-51aa7b17a6fb.999161.xyz
    tls: true
  - type: trojan
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_8
    server: ip.sb
    port: 443
    password: trojan
    network: ws
    sni: nixian.pages.dev
    fingerprint: random
    tls: true
    ws-opts:
      path: /?ed=2560/?Join-sho--Telegram--VITUREY-Join-sho--Telegram--VITUREY-Join-sho--Telegram--VITUREY-Join-sho--Telegram--VITUREY-Join-sho--Telegram--VITUREY-Join-sho--Telegram--VITUREY-Join-sho--Telegram--VITUREY-Join-sho--Telegram--VITUREY-Join-sho--Telegram--VITUREY-Join-sho--Telegram--VITUREY-Join-sho--Telegram--VITUREY-
      headers:
        Host: nixian.pages.dev
  - type: vmess
    name: ğŸ‡©ğŸ‡ª å¾·å›½ 33
    server: 141.101.121.250
    port: 80
    uuid: d967ffca-de90-4daa-bd00-d527e5bae11f
    alterId: 0
    network: ws
    cipher: auto
    servername: google.whatsapp.snapp.torob.basalam.leoshopping77.ir.
    ws-opts:
      path: /?BIA_TELEGRAM (@AZARBAYJAB1) TM (@AZARBAYJAB1) TM (@AZARBAYJAB1) TM
        (@AZARBAYJAB1) TM (@AZARBAYJAB1) TM (@AZARBAYJAB1)
      headers:
        Host: google.whatsapp.snapp.torob.basalam.leoshopping77.ir.
    tls: true
  - type: vmess
    name: DE_555fe_0004
    server: 77.37.33.108
    port: 80
    uuid: d967ffca-de90-4daa-bd00-d527e5bae11f
    alterId: 0
    network: ws
    cipher: auto
    servername: google.whatsapp.snapp.torob.basalam.leoshopping77.ir.
    ws-opts:
      path: /
      headers:
        Host: google.whatsapp.snapp.torob.basalam.leoshopping77.ir.
    tls: true
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_3_1
    server: 36.150.215.236
    port: 4492
    password: BxceQaOe
    network: tcp
    skip-cert-verify: true
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_5
    server: 117.172.176.24
    port: 1332
    password: bca467b8c15211d189008a93c7519d3b
    network: tcp
    sni: www.nintendogames.net
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_6
    server: 36.150.215.197
    port: 51825
    password: BxceQaOe
    network: tcp
    skip-cert-verify: true
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_7
    server: 36.151.251.47
    port: 53743
    password: BxceQaOe
    network: tcp
    skip-cert-verify: true
  - type: vmess
    name: ğŸ‡®ğŸ‡¹ æ„å¤§åˆ© 01
    server: v5.heduian.link
    port: 30805
    uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
    alterId: 2
    network: tcp
    cipher: auto
    tls: true
  - type: vmess
    name: "%F0%9D%92%83%F0%9D%92%90%F0%9D%92%8D%F0%9D%92%83%F0%9D%92%90%F0%9D%92%8D\
      %F0%9D%92%97%F0%9D%92%91%F0%9D%92%8F-%40bolbolservice"
    server: ksadk/23.korosh.shop
    port: 2060
    uuid: 1648bc92-d210-4d17-9174-710231d5b23e
    alterId: 0
    network: tcp
    cipher: auto
    tls: true
  - type: ss
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_8
    server: 103.149.183.154
    port: 8388
    cipher: chacha20-ietf
    password: asd123456
  - type: vmess
    name: AUğŸ‡¦ğŸ‡º | arda101.ardaserver.site-34167 | 275.19ms
    server: arda101.ardaserver.site
    port: 34167
    uuid: 571cd4a3-e2af-4bab-a6f5-3b5906afc111
    alterId: 0
    network: tcp
    cipher: auto
    tls: true
  - type: vmess
    name: ğŸ‡­ğŸ‡° HK_89
    server: 77e1818c-t13gg0-t5fh9u-1uni.hk3.p5pv.com
    port: 80
    uuid: adbd0a82-3336-11ed-bd7c-f23c913c8d2b
    alterId: 2
    network: ws
    cipher: auto
    servername: broadcastlv.chat.bilibili.com
    ws-opts:
      path: /
      headers:
        Host: broadcastlv.chat.bilibili.com
    tls: true
  - type: vmess
    name: ğŸ‡­ğŸ‡° HK_324
    server: 10cd2f16-sv2sg0-t7hu58-1q1la.hk3.p5pv.com
    port: 80
    uuid: 25b46954-9a33-11ee-8b86-f23c91cfbbc9
    alterId: 2
    network: ws
    cipher: auto
    servername: broadcastlv.chat.bilibili.com
    ws-opts:
      path: /
      headers:
        Host: broadcastlv.chat.bilibili.com
    tls: true
  - type: vmess
    name: ğŸ‡­ğŸ‡°HK-219.77.235.50-1213
    server: 2e617951-sv2sg0-taj9mo-1tco3.hk3.p5pv.com
    port: 80
    uuid: e29de954-ea01-11ef-a271-f23c91cfbbc9
    alterId: 2
    network: ws
    cipher: auto
    servername: broadcastlv.chat.bilibili.com
    ws-opts:
      path: /
      headers:
        Host: broadcastlv.chat.bilibili.com
    tls: true
  - type: vmess
    name: ğŸ‡­ğŸ‡° HK_213
    server: a731a8b3-sv2sg0-sy1a0y-1iyov.hk3.p5pv.com
    port: 80
    uuid: 33629870-e57e-11ec-bb74-f23c9164ca5d
    alterId: 2
    network: ws
    cipher: auto
    servername: broadcastlv.chat.bilibili.com
    ws-opts:
      path: /
      headers:
        Host: broadcastlv.chat.bilibili.com
    tls: true
  - type: vmess
    name: ğŸ‡­ğŸ‡° HK_210
    server: 9d27188f-t00kg0-t9byd7-1jfvb.hk3.p5pv.com
    port: 80
    uuid: 06b2ac52-fcc6-11ec-bb74-f23c9164ca5d
    alterId: 2
    network: ws
    cipher: auto
    servername: broadcastlv.chat.bilibili.com
    ws-opts:
      path: /
      headers:
        Host: broadcastlv.chat.bilibili.com
    tls: true
  - type: vmess
    name: ğŸ‡­ğŸ‡° HK_231
    server: 360de725-sv4n40-t2y63q-1jk6u.hk3.p5pv.com
    port: 80
    uuid: 45bc25b2-1a10-11ed-91c0-f23c91cfbbc9
    alterId: 2
    network: ws
    cipher: auto
    servername: broadcastlv.chat.bilibili.com
    ws-opts:
      path: /
      headers:
        Host: broadcastlv.chat.bilibili.com
    tls: true
  - type: vmess
    name: ğŸ‡­ğŸ‡°HK-219.77.235.50-1223
    server: 7f346235-sv4n40-t76x2i-wj6v.hk3.p5pv.com
    port: 80
    uuid: 847c03b2-0a9d-11eb-a8bf-f23c91cfbbc9
    alterId: 2
    network: ws
    cipher: auto
    servername: broadcastlv.chat.bilibili.com
    ws-opts:
      path: /
      headers:
        Host: broadcastlv.chat.bilibili.com
    tls: true
  - type: vmess
    name: ğŸ‡­ğŸ‡°HK-219.77.235.50-1226
    server: 6dbaea45-sv0xs0-t9i7o2-1lt20.hk3.p5pv.com
    port: 80
    uuid: bf4ec108-f2b7-11ef-b654-f23c91cfbbc9
    alterId: 2
    network: ws
    cipher: auto
    servername: broadcastlv.chat.bilibili.com
    ws-opts:
      path: /
      headers:
        Host: broadcastlv.chat.bilibili.com
    tls: true
  - type: vmess
    name: ğŸ‡­ğŸ‡°HK-219.77.235.50-1215
    server: 00711758-sva740-tbrhck-1thqb.hk3.p5pv.com
    port: 80
    uuid: 4f4c6876-fcf6-11ef-94aa-f23c913c8d2b
    alterId: 2
    network: ws
    cipher: auto
    servername: broadcastlv.chat.bilibili.com
    ws-opts:
      path: /
      headers:
        Host: broadcastlv.chat.bilibili.com
    tls: true
  - type: vmess
    name: ğŸ‡­ğŸ‡° HK_72
    server: d5dc60aa-t0kxs0-t1nwsn-1la2q.hk3.p5pv.com
    port: 80
    uuid: 431026c8-7397-11ed-a8bf-f23c91cfbbc9
    alterId: 2
    network: ws
    cipher: auto
    servername: broadcastlv.chat.bilibili.com
    ws-opts:
      path: /
      headers:
        Host: broadcastlv.chat.bilibili.com
    tls: true
  - type: vmess
    name: ğŸ‡­ğŸ‡° HK_86
    server: f0364aea-t13gg0-t1rksu-1ssud.hk3.p5pv.com
    port: 80
    uuid: e6aa39b6-f0b5-11ef-bca1-f23c91cfbbc9
    alterId: 2
    network: ws
    cipher: auto
    servername: broadcastlv.chat.bilibili.com
    ws-opts:
      path: /
      headers:
        Host: broadcastlv.chat.bilibili.com
    tls: true
  - type: vmess
    name: ğŸ‡­ğŸ‡°HK-219.77.235.50-1220
    server: 4c2c02b9-sv2sg0-sv75lj-1swf9.hk3.p5pv.com
    port: 80
    uuid: 2bb1edc8-fa5d-11ef-9dd9-f23c9164ca5d
    alterId: 2
    network: ws
    cipher: auto
    servername: broadcastlv.chat.bilibili.com
    ws-opts:
      path: /
      headers:
        Host: broadcastlv.chat.bilibili.com
    tls: true
  - type: vmess
    name: ğŸ‡­ğŸ‡°HK-219.77.235.50-1224
    server: 6bdf8f31-sv2sg0-tdh9w7-ahsb.hk3.p5pv.com
    port: 80
    uuid: 2e42c1ee-aaaa-11ec-bb74-f23c9164ca5d
    alterId: 2
    network: ws
    cipher: auto
    servername: broadcastlv.chat.bilibili.com
    ws-opts:
      path: /
      headers:
        Host: broadcastlv.chat.bilibili.com
    tls: true
  - type: vmess
    name: ğŸ‡­ğŸ‡° HK_83
    server: 64309899-t15b40-t2c3sq-1spnr.hk3.p5pv.com
    port: 80
    uuid: 127e3f92-f714-11ef-bbb0-f23c91cfbbc9
    alterId: 2
    network: ws
    cipher: auto
    servername: broadcastlv.chat.bilibili.com
    ws-opts:
      path: /
      headers:
        Host: broadcastlv.chat.bilibili.com
    tls: true
  - type: ss
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_1_1
    server: sl.fgmcx.top
    port: 41047
    cipher: chacha20-ietf-poly1305
    password: 014e90df-a3ee-4654-a9f6-d118e02dd02a
  - type: vmess
    name: ğŸ‡­ğŸ‡°HK-219.77.235.50-1229
    server: dfed4efb-t4n8g0-t636g9-luwe.hk3.p5pv.com
    port: 80
    uuid: a2b0fd2b-716f-0df8-d4e2-03a1c00e5f1a
    alterId: 2
    network: ws
    cipher: auto
    servername: broadcastlv.chat.bilibili.com
    ws-opts:
      path: /
      headers:
        Host: broadcastlv.chat.bilibili.com
    tls: true
  - type: vmess
    name: ğŸ‡­ğŸ‡°HK-219.77.235.50-1214
    server: 1dd7778a-sv4n40-szxh9w-46gc.hk3.p5pv.com
    port: 80
    uuid: 225d1cca-d744-11ef-b790-f23c91cfbbc9
    alterId: 2
    network: ws
    cipher: auto
    servername: broadcastlv.chat.bilibili.com
    ws-opts:
      path: /
      headers:
        Host: broadcastlv.chat.bilibili.com
    tls: true
  - type: vmess
    name: ğŸ‡­ğŸ‡° HK_108
    server: 45c56923-sucv40-tcop2n-tl32.hk3.p5pv.com
    port: 80
    uuid: 5c02ab88-7b9c-11ea-8fc9-f23c913c8d2b
    alterId: 2
    network: ws
    cipher: auto
    servername: broadcastlv.chat.bilibili.com
    ws-opts:
      path: /
      headers:
        Host: broadcastlv.chat.bilibili.com
    tls: true
  - type: vmess
    name: ğŸ‡­ğŸ‡° HK_171
    server: b8ffcda3-sv2sg0-sv37gm-81nv.hk3.p5pv.com
    port: 80
    uuid: 47e91fb6-25b8-df52-bc18-3cdc8548192f
    alterId: 2
    network: ws
    cipher: auto
    servername: broadcastlv.chat.bilibili.com
    ws-opts:
      path: /
      headers:
        Host: broadcastlv.chat.bilibili.com
    tls: true

