# åˆ›å»ºè€…ï¼šç”¨æˆ·è‡ªå®šä¹‰èŠ‚ç‚¹é…ç½®
# åˆ›å»ºæ—¶é—´ï¼š2025-09-27 08:00:00

# å•èŠ‚ç‚¹é…ç½®
proxies:
  - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½
    type: vless
    server: 151.101.3.8
    port: 80
    uuid: dd0cfef0-fda9-47ec-8a65-49d7bc004f82
    network: ws
    tls: false
    ws-opts:
      path: /---@MiTiVPN/---@MiTiVPN/---@MiTiVPN/---@MiTiVPN/---@MiTiVPN
      headers:
        Host: mitivpn.global.ssl.fastly.net
  - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_1
    type: vless
    server: cloudflare.182682.xyz
    port: 443
    uuid: 3e2e3c21-3fc8-468f-9ab5-e782bdf5bf97
    network: ws
    servername: l.ayovo.netlib.re
    tls: true
    client-fingerprint: chrome
    ws-opts:
      path: /?ed=2560
      headers:
        Host: l.ayovo.netlib.re
  - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_2
    type: vless
    server: 162.159.16.63
    port: 443
    uuid: 3e2e3c21-3fc8-468f-9ab5-e782bdf5bf97
    network: ws
    servername: l.ayovo.netlib.re
    tls: true
    client-fingerprint: chrome
    ws-opts:
      path: /?ed=2560
      headers:
        Host: l.ayovo.netlib.re
  - name: ğŸ‡©ğŸ‡ª_DE_å¾·å›½
    type: vless
    server: api.dark-coffe.com
    port: 2096
    uuid: 7e58699f-1d5d-4f6b-b181-cb74f0ad9509
    network: ws
    servername: TzS7v35LfD.sMaRtTeChZaAl.InFo
    tls: true
    client-fingerprint: chrome
    ws-opts:
      path: /
      headers:
        Host: TzS7v35LfD.sMaRtTeChZaAl.InFo
  - name: ğŸ‡©ğŸ‡ª_DE_å¾·å›½_1
    type: vless
    server: api.dark-coffe.com
    port: 443
    uuid: 7e58699f-1d5d-4f6b-b181-cb74f0ad9509
    network: ws
    servername: GfV5t2331T.sMaRtTeChZaAl.InFo
    tls: true
    client-fingerprint: chrome
    ws-opts:
      path: /
      headers:
        Host: GfV5t2331T.sMaRtTeChZaAl.InFo
  - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_3
    type: vless
    server: 104.16.250.22
    port: 443
    uuid: 3e2e3c21-3fc8-468f-9ab5-e782bdf5bf97
    network: ws
    servername: l.ayovo.netlib.re
    tls: true
    client-fingerprint: chrome
    ws-opts:
      path: /?ed=2560
      headers:
        Host: l.ayovo.netlib.re
  - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_4
    type: vless
    server: 162.159.45.232
    port: 443
    uuid: 3e2e3c21-3fc8-468f-9ab5-e782bdf5bf97
    network: ws
    servername: l.ayovo.netlib.re
    tls: true
    ws-opts:
      path: /?ed=2560
      headers:
        Host: l.ayovo.netlib.re
  - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_5
    type: vless
    server: 104.21.224.5
    port: 443
    uuid: 3e2e3c21-3fc8-468f-9ab5-e782bdf5bf97
    network: ws
    servername: l.ayovo.netlib.re
    tls: true
    client-fingerprint: chrome
    ws-opts:
      path: /?ed=2560
      headers:
        Host: l.ayovo.netlib.re
  - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_6
    type: vless
    server: 104.17.25.173
    port: 443
    uuid: 3e2e3c21-3fc8-468f-9ab5-e782bdf5bf97
    network: ws
    servername: l.ayovo.netlib.re
    tls: true
    client-fingerprint: chrome
    ws-opts:
      path: /?ed=2560
      headers:
        Host: l.ayovo.netlib.re
  - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_7
    type: vless
    server: 104.18.185.26
    port: 443
    uuid: 3e2e3c21-3fc8-468f-9ab5-e782bdf5bf97
    network: ws
    servername: l.ayovo.netlib.re
    tls: true
    ws-opts:
      path: /?ed=2560
      headers:
        Host: l.ayovo.netlib.re
  - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_8
    type: vless
    server: 162.159.44.142
    port: 443
    uuid: 3e2e3c21-3fc8-468f-9ab5-e782bdf5bf97
    network: ws
    servername: l.ayovo.netlib.re
    tls: true
    client-fingerprint: chrome
    ws-opts:
      path: /?ed=2560
      headers:
        Host: l.ayovo.netlib.re
  - name: ğŸ‡©ğŸ‡ª_DE_å¾·å›½_2
    type: vless
    server: api.dark-coffe.com
    port: 2087
    uuid: 7e58699f-1d5d-4f6b-b181-cb74f0ad9509
    network: ws
    servername: 5JxGp6VrFh.SmArTtEcHzAaL.iNfO
    tls: true
    ws-opts:
      path: /?ed=2048HiByeVPNN--HiByeVPNN--HiByeVPNN--HiByeVPNN--HiByeVPNN--HiByeVPNN--HiByeVPNN--HiByeVPNN--HiByeVPNN--HiByeVPNN--HiByeVPNN--HiByeVPNN--HiByeVPNN
      headers:
        Host: 5JxGp6VrFh.SmArTtEcHzAaL.iNfO
  - name: ğŸ‡©ğŸ‡ª_DE_å¾·å›½_3
    type: vless
    server: 5.10.214.5
    port: 443
    uuid: 7e58699f-1d5d-4f6b-b181-cb74f0ad9509
    network: ws
    servername: GfV5t2331T.sMaRtTeChZaAl.InFo
    tls: true
    client-fingerprint: chrome
    ws-opts:
      path: /
      headers:
        Host: GfV5t2331T.sMaRtTeChZaAl.InFo
  - name: ğŸ‡©ğŸ‡ª_DE_å¾·å›½_4
    type: vless
    server: 5.10.214.5
    port: 2087
    uuid: 7e58699f-1d5d-4f6b-b181-cb74f0ad9509
    network: ws
    servername: 5JxGp6VrFh.SmArTtEcHzAaL.iNfO
    tls: true
    client-fingerprint: chrome
    ws-opts:
      path: /
      headers:
        Host: 5JxGp6VrFh.SmArTtEcHzAaL.iNfO
  - name: ğŸ‡©ğŸ‡ª_DE_å¾·å›½_5
    type: vless
    server: 5.10.214.0
    port: 2096
    uuid: 7e58699f-1d5d-4f6b-b181-cb74f0ad9509
    network: ws
    servername: TzS7v35LfD.sMaRtTeChZaAl.InFo
    tls: true
    client-fingerprint: chrome
    ws-opts:
      path: /
      headers:
        Host: TzS7v35LfD.sMaRtTeChZaAl.InFo
