# åˆ›å»ºè€…ï¼šç”¨æˆ·è‡ªå®šä¹‰èŠ‚ç‚¹é…ç½®
# åˆ›å»ºæ—¶é—´ï¼š2025-09-27 08:00:00

# å•èŠ‚ç‚¹é…ç½®
proxies:
  - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½
    type: vless
    server: 104.25.92.205
    port: 443
    uuid: 2a667767-995c-4892-9719-f52c3db2b0f2
    network: ws
    servername: sanYUuu.paGES.dEV
    tls: true
    client-fingerprint: chrome
    ws-opts:
      path: /eyJqdW5rIjoiQVpjSG1wcDBtd0lHbm05byIsInByb3RvY29sIjoidmwiLCJtb2RlIjoicHJveHlpcCIsInBhbmVsSVBzIjpbXX0=?ed=2560
      headers:
        Host: sanyuuu.pages.dev
  - name: ğŸ‡©ğŸ‡°_DK_ä¸¹éº¦
    type: vless
    server: 159.195.60.150
    port: 2053
    uuid: f81fac6d-88e7-45e3-b19e-084527859fba
    network: ws
    servername: info.marfanet.com
    tls: true
    client-fingerprint: firefox
    ws-opts:
      path: /api/v1/events
      headers:
        Host: info.marfanet.com
  - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_1
    type: vless
    server: 144.31.232.241
    port: 2083
    uuid: c501c66b-c6c2-456b-b604-80393b83d67f
    network: grpc
    servername: apple.com
    tls: true
    client-fingerprint: chrome
    grpc-opts:
      grpc-service-name: UpdateService
    reality-opts:
      public-key: J6NuOlIq3ypdTFc1TMhDDKmF8BWPnNWZq1EkxD7K-lQ
      short-id: 6da16b1335651b38
  - name: ğŸ‡·ğŸ‡º_RU_ä¿„ç½—æ–¯
    type: vless
    server: 217.16.27.217
    port: 443
    uuid: eb071647-72a6-46be-8e89-ff3d228d52f6
    servername: api-maps.yandex.ru
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    reality-opts:
      public-key: FkmYFobwxLMLEktYXywmjthuEYCZggITsxwPNasTKUg
      short-id: a76ea384b29a4f79
  - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_2
    type: vless
    server: 45.15.128.75
    port: 8443
    uuid: fad2b7e0-d80c-4b7b-a84f-d86e0e49f627
    servername: max.ru
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    reality-opts:
      public-key: BSsqyfTD-avgb1CyUdy_qJA95HwyMadBMJt7-EQjggk
      short-id: e473bbc75224b9df
  - name: ğŸ‡·ğŸ‡º_RU_ä¿„ç½—æ–¯_1
    type: vless
    server: 5.188.224.116
    port: 2083
    uuid: c501c66b-c6c2-456b-b604-80393b83d67f
    network: grpc
    servername: ir.ozone.ru
    tls: true
    client-fingerprint: chrome
    grpc-opts:
      grpc-service-name: UpdateService
    reality-opts:
      public-key: J6NuOlIq3ypdTFc1TMhDDKmF8BWPnNWZq1EkxD7K-lQ
      short-id: 6da16b1335651b38
  - name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½
    type: vless
    server: 114.32.9.249
    port: 16443
    uuid: 3e974f9e-f568-4c2a-a4db-e9b666b4ea9e
    network: ws
    servername: 63.hhhhh.eu.org
    tls: true
    client-fingerprint: chrome
    ws-opts:
      path: /114.32.9.249:16443
      headers:
        Host: 63.hhhhh.eu.org
  - name: ğŸ‡·ğŸ‡º_RU_ä¿„ç½—æ–¯_2
    type: vless
    server: 37.139.35.53
    port: 443
    uuid: c501c66b-c6c2-456b-b604-80393b83d67f
    network: grpc
    servername: eh.vk.com
    tls: true
    client-fingerprint: chrome
    grpc-opts:
      grpc-service-name: UpdateService
    reality-opts:
      public-key: _oEGDYSSHrqmbHEUoHbp6YnmNTcXTVdWXcDmpi3JdH0
      short-id: aefbcf7fc283bd55
  - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_3
    type: vless
    server: 198.62.62.248
    port: 443
    uuid: 5a4abb78-ecd7-4d68-ab2a-c11a3842f261
    network: ws
    servername: tar.alabama-tigr.info
    tls: true
    client-fingerprint: chrome
    ws-opts:
      path: /love
      headers:
        Host: tar.alabama-tigr.info
  - name: ğŸ‡¨ğŸ‡¦_CA_åŠ æ‹¿å¤§
    type: vless
    server: 142.248.80.157
    port: 443
    uuid: 4aff5de5-83dc-43c9-a33e-10e6fdb90ed2
    servername: apple.com
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    reality-opts:
      public-key: Wvt6tuMcFY9rWF2BsdAD4DXgLAoxQJxHWlao2BPR23Y
  - name: ğŸ‡§ğŸ‡ª_BE_æ¯”åˆ©æ—¶->ğŸ‡¬ğŸ‡§_GB_è‹±å›½
    type: vless
    server: 143.20.236.51
    port: 443
    uuid: d65cc14c-f53f-4fe2-b262-97856601319c
    servername: yahoo.com
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    reality-opts:
      public-key: e2RLf57Li_-MDZGE9ss1BWPgP54mqRb5PfXhW2jcVVg
      short-id: c39cc7310a
  - name: æœªçŸ¥
    type: ss
    server: 103.186.155.44
    port: 38388
    cipher: aes-256-cfb
    password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  - name: ğŸ‡©ğŸ‡ª_DE_å¾·å›½
    type: vless
    server: xboxgame-dl.com
    port: 433
    uuid: af338e79-8259-4662-a0ff-db6df2414501
    servername: xboxgame-dl.com
    tls: true
    client-fingerprint: chrome
    reality-opts:
      public-key: J6v3yhXsfUyoPDmw3Beq9YSxqlW2Ir_5PpULj1xQX2E
      short-id: 8d4981fb6742b104
  - name: æœªçŸ¥_1
    type: ss
    server: 103.186.154.245
    port: 38388
    cipher: aes-256-cfb
    password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  - name: ğŸ‡·ğŸ‡º_RU_ä¿„ç½—æ–¯->ğŸ‡©ğŸ‡ª_DE_å¾·å›½
    type: vless
    server: WangCai2@193.37.70.63
    port: 443
    uuid: "TelegramğŸ‡¨ğŸ‡³ "
    network: ws
    servername: tn1rr.qzz.io
    tls: true
    ws-opts:
      path: /sg-lnd
      headers:
        Host: tn1rr.qzz.io
  - name: ğŸ‡®ğŸ‡¶_IQ_ä¼Šæ‹‰å…‹
    type: vless
    server: deu469.unboundworld.org
    port: 443
    uuid: cc9f7840-757a-430b-bddc-a73478bea434
    servername: www.t3n.de
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    reality-opts:
      public-key: BhTJ3phnq-Z-10aFKSsj1lzhA8mULR4L6leE4-0WTAs
  - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_4
    type: vless
    server: 144.31.18.73
    port: 2083
    uuid: c501c66b-c6c2-456b-b604-80393b83d67f
    network: grpc
    servername: apple.com
    tls: true
    client-fingerprint: chrome
    grpc-opts:
      grpc-service-name: UpdateService
    reality-opts:
      public-key: J6NuOlIq3ypdTFc1TMhDDKmF8BWPnNWZq1EkxD7K-lQ
      short-id: 6da16b1335651b38
  - name: ğŸ‡·ğŸ‡º_RU_ä¿„ç½—æ–¯_3
    type: vless
    server: regall.appav.online
    port: 2083
    uuid: c501c66b-c6c2-456b-b604-80393b83d67f
    network: grpc
    servername: ads.x5.ru
    tls: true
    client-fingerprint: chrome
    grpc-opts:
      grpc-service-name: UpdateService
    reality-opts:
      public-key: J6NuOlIq3ypdTFc1TMhDDKmF8BWPnNWZq1EkxD7K-lQ
      short-id: 6da16b1335651b38
  - name: ğŸ‡¬ğŸ‡§_GB_è‹±å›½->ğŸ‡©ğŸ‡ª_DE_å¾·å›½
    type: vless
    server: 51.250.4.119
    port: 443
    uuid: 9a599b2e-5455-44d5-9a72-5c76f28e93e3
    servername: ads.x5.ru
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: qq
    reality-opts:
      public-key: FkmYFobwxLMLEktYXywmjthuEYCZggITsxwPNasTKUg
      short-id: 2476f063981ffd92
  - name: ğŸ‡¬ğŸ‡·_GR_å¸Œè…Š
    type: vless
    server: 185.234.57.216
    port: 443
    uuid: b824f264-8cc3-4669-9f60-47b51ed1aa11
    servername: yahoo.com
    tls: true
    client-fingerprint: chrome
    reality-opts:
      public-key: 2Z2meC9rRAMD3k52ne8dh8PdfRNpOs5T9yObPyFkXyQ
      short-id: f9fe
  - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_5
    type: vless
    server: 50.117.3.143
    port: 443
    uuid: c501c66b-c6c2-456b-b604-80393b83d67f
    servername: apple.com
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    reality-opts:
      public-key: 9ajY_OBOn5CCPnCJTPjxg6J3IWE8uJYAiWQvG9CBGjU
      short-id: 00684d2eae2cdd16
  - name: æœªçŸ¥_2
    type: ss
    server: 103.186.154.218
    port: 38388
    cipher: aes-256-cfb
    password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  - name: æœªçŸ¥_3
    type: ss
    server: 103.186.154.155
    port: 38388
    cipher: aes-256-cfb
    password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_6
    type: vless
    server: 3.cdnconn.com
    port: 23335
    uuid: e384913f-8863-47b4-8858-a84b68abb4a6
    servername: icloud.com
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    reality-opts:
      public-key: 7Gi8eiUU9TIVbGuvSU16gl5-Aqt7tcCSB9x6CSxyvik
      short-id: 67b1e94e4dd1ef90
  - name: ğŸ‡³ğŸ‡±_NL_è·å…°
    type: vless
    server: s502.okgg.top
    port: 443
    uuid: 8c6118b9-78a8-3b3b-a49a-6aa9cb5b1d4e
    servername: u708330uc21fs502.okgg.top
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: random
  - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_7
    type: vless
    server: 47.80.12.87
    port: 443
    uuid: 3e7f67de-648e-4871-b51a-a225214d41ee
    servername: api.company-target.com
    tls: true
    client-fingerprint: chrome
    reality-opts:
      public-key: TRP10HqKUXEQ3O-cfsq93DycfBmbJe9KM36yvSa8Mmw
