# åˆ›å»ºè€…ï¼šç”¨æˆ·è‡ªå®šä¹‰èŠ‚ç‚¹é…ç½®
# åˆ›å»ºæ—¶é—´ï¼š2025-09-27 08:00:00

# å•èŠ‚ç‚¹é…ç½®
proxies:
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½
    server: oss-cn-shanghai.letssepub.com
    port: 20021
    password: adbac894-90b9-4913-b77e-a715a8d4ebc8
    network: tcp
    sni: dingding-doc.com
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_1
    server: 36.150.215.137
    port: 5156
    password: BxceQaOe
    network: tcp
    sni: t.me/ripaojiedian
    skip-cert-verify: true
  - type: vmess
    name: ğŸ‡¸ğŸ‡¬SGÂ²_1|4.1MB/s|GPTâº|YT|NF|GM|7%
    server: xcsgp.cokecloud.top
    port: 25878
    uuid: 16bdb787-7a82-4e35-a7a3-e0821b3a50bf
    alterId: 0
    network: tcp
    cipher: auto
    tls: true
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_2
    server: 36.150.215.231
    port: 1655
    password: BxceQaOe
    network: tcp
    sni: t.me/ripaojiedian
    skip-cert-verify: true
  - type: ss
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_3
    server: cokecloudjp.cokecloud.top
    port: 13215
    cipher: chacha20-ietf-poly1305
    password: 16bdb787-7a82-4e35-a7a3-e0821b3a50bf
  - type: vmess
    name: ğŸ‡­ğŸ‡°HKÂ²_2|1.4MB/s|GPTâº|YT|NF|D+|GM|0%|KeepSucced
    server: xctransfer1st.cokecloud.top
    port: 12672
    uuid: 16bdb787-7a82-4e35-a7a3-e0821b3a50bf
    alterId: 0
    network: tcp
    cipher: auto
    tls: true
  - type: hysteria
    name: ğŸ‡«ğŸ‡·_FR_æ³•å›½
    server: 195.154.200.40
    port: 15010
    protocol: udp
    alpn:
      - '["h3"]'
  - type: vmess
    name: ğŸ‡­ğŸ‡°HKÂ²_5|7.5MB/s|GPTâº|YT|NF|D+|2%
    server: a05447bd-t5d5s0-t6z0et-1t60o.hk3.p5pv.com
    port: 80
    uuid: ce481c6e-f4c8-11ef-bbb0-f23c91cfbbc9
    alterId: 2
    network: ws
    cipher: auto
    servername: broadcastlv.chat.bilibili.com
    ws-opts:
      path: /
      headers:
        Host: broadcastlv.chat.bilibili.com
    tls: true
  - type: vmess
    name: ğŸ‡¹ğŸ‡¼TWÂ²_1|1.2MB/s|GPTâº|YT|NF|GM|25%|KeepSucced
    server: xdtw.cokecloud.top
    port: 13255
    uuid: 16bdb787-7a82-4e35-a7a3-e0821b3a50bf
    alterId: 0
    network: tcp
    cipher: auto
    tls: true
  - type: ss
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_4
    server: idtf.cokecloud.top
    port: 32725
    cipher: chacha20-ietf-poly1305
    password: 16bdb787-7a82-4e35-a7a3-e0821b3a50bf
  - type: vmess
    name: ğŸ‡­ğŸ‡°HKÂ²_2|2.5MB/s|GPTâº|YT|NF|GM|7%
    server: xctransfer1st.cokecloud.top
    port: 44489
    uuid: 16bdb787-7a82-4e35-a7a3-e0821b3a50bf
    alterId: 0
    network: tcp
    cipher: auto
    tls: true
  - type: ss
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_5
    server: xdtw.cokecloud.top
    port: 21073
    cipher: chacha20-ietf-poly1305
    password: 16bdb787-7a82-4e35-a7a3-e0821b3a50bf
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_6
    server: 36.150.215.137
    port: 9713
    password: BxceQaOe
    network: tcp
    sni: t.me/ripaojiedian
    skip-cert-verify: true
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_7
    server: 117.172.176.23
    port: 316
    password: e4e262d453466988575c397a30562337
    network: tcp
    sni: www.nintendogames.net
  - type: vmess
    name: ğŸ‡­ğŸ‡°HKÂ²_8|6.8MB/s|GPTâº|YT|NF|D+|GM|8%|KeepHistory
    server: xctransfer1st.cokecloud.top
    port: 45861
    uuid: 16bdb787-7a82-4e35-a7a3-e0821b3a50bf
    alterId: 0
    network: tcp
    cipher: auto
    tls: true
  - type: hysteria
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½
    server: 51.159.226.1
    port: 49003
    protocol: udp
    alpn:
      - '["h3"]'
  - type: hysteria2
    name: ğŸ‡°ğŸ‡·_KR_éŸ©å›½
    server: 6bkr1.6bnw.top
    port: 10100
    password: 4a6bf640-5c5e-41d3-8078-89a12174cf57
    skip-cert-verify: true
    sni: 6bkr1.6bnw.top
  - type: vmess
    name: ğŸ‡¸ğŸ‡¬SGÂ²_2|1.4MB/s|GPTâº|YT|NF|D+|GM|7%|KeepSucced
    server: xcsgp.cokecloud.top
    port: 10420
    uuid: 16bdb787-7a82-4e35-a7a3-e0821b3a50bf
    alterId: 0
    network: tcp
    cipher: auto
    tls: true
  - type: ss
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_8
    server: cokecloudjp.cokecloud.top
    port: 43291
    cipher: chacha20-ietf-poly1305
    password: 16bdb787-7a82-4e35-a7a3-e0821b3a50bf
  - type: vmess
    name: ğŸ‡­ğŸ‡°HKÂ²_6|7.1MB/s|GPTâº|YT|NF|D+|GM|8%|KeepHistory
    server: xctransfer1st.cokecloud.top
    port: 38630
    uuid: 16bdb787-7a82-4e35-a7a3-e0821b3a50bf
    alterId: 0
    network: tcp
    cipher: auto
    tls: true
  - type: vmess
    name: ğŸ‡­ğŸ‡°HKÂ²_3|4.3MB/s|GPTâº|YT|NF|D+|GM|8%
    server: xctransfer1st.cokecloud.top
    port: 33575
    uuid: 16bdb787-7a82-4e35-a7a3-e0821b3a50bf
    alterId: 0
    network: tcp
    cipher: auto
    tls: true
  - type: ss
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_9
    server: cokecloudjp.cokecloud.top
    port: 40793
    cipher: chacha20-ietf-poly1305
    password: 16bdb787-7a82-4e35-a7a3-e0821b3a50bf
  - type: vmess
    name: ğŸ‡­ğŸ‡°HKÂ²_10|6.4MB/s|GPTâº|YT|NF|D+|8%|KeepHistory
    server: xctransfer1st.cokecloud.top
    port: 45449
    uuid: 16bdb787-7a82-4e35-a7a3-e0821b3a50bf
    alterId: 0
    network: tcp
    cipher: auto
    tls: true
  - type: vmess
    name: ğŸ‡­ğŸ‡°HKÂ²_4|1.0MB/s|GPTâº|YT|NF|D+|GM|7%|KeepSucced
    server: xctransfer1st.cokecloud.top
    port: 21552
    uuid: 16bdb787-7a82-4e35-a7a3-e0821b3a50bf
    alterId: 0
    network: tcp
    cipher: auto
    tls: true
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_1
    server: www.wto.org
    port: 2095
    uuid: 86c50e3a-5b87-49dd-bd20-03c7f2735e40
    network: ws
    servername: fuckingfangbinxing.pusytroller.cf
    encryption: none
    ws-opts:
      path: /
      headers:
        Host: fuckingfangbinxing.pusytroller.cf
  - type: vmess
    name: ğŸ‡­ğŸ‡°HK-203.198.28.145-1002
    server: aflzzul.meiquankongjian.com
    port: 52513
    uuid: 342bacfd-2b8f-3f49-a16e-439db5b0b9d5
    alterId: 0
    network: ws
    cipher: auto
    servername: aflzzul.meiquankongjian.com
    ws-opts:
      path: /564dfa20/
      headers:
        Host: aflzzul.meiquankongjian.com
    tls: true
  - type: ss
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_10
    server: hg02.gnzzrk001.top
    port: 12036
    cipher: chacha20-ietf-poly1305
    password: dc9ea653-becc-44f1-95f9-16773a0519e9
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_11
    server: 36.150.215.245
    port: 9269
    password: BxceQaOe
    network: tcp
    sni: t.me/ripaojiedian
    skip-cert-verify: true
  - type: hysteria2
    name: ğŸ‡·ğŸ‡º_RU_ä¿„ç½—æ–¯
    server: kr2.jueduibupao.top
    port: 30000
    password: 4a6bf640-5c5e-41d3-8078-89a12174cf57
    skip-cert-verify: true
    sni: kr2.jueduibupao.top
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_1
    server: oss-cn-shanghai.letssepub.com
    port: 20021
    password: adbac894-90b9-4913-b77e-a715a8d4ebc8
    network: tcp
    sni: dingding-doc.com
  - type: vmess
    name: ğŸ‡¸ğŸ‡¬SGÂ²_1|4.7MB/s|GPTâº|YT-US|NF|GM|26%|KeepHistory
    server: gtm1.ktmwan.net
    port: 12901
    uuid: 0d36b2c4-a554-4e54-bd53-1975fc960ba6
    alterId: 0
    network: ws
    cipher: auto
    servername: gtm1.ktmwan.net
    ws-opts:
      path: /
      headers:
        Host: gtm1.ktmwan.net
    tls: true
  - type: hysteria
    name: ğŸ‡«ğŸ‡·_FR_æ³•å›½_1
    server: 195.154.200.40
    port: 15010
    protocol: udp
    alpn:
      - '["h3"]'
  - type: vmess
    name: ğŸ‡­ğŸ‡°HKÂ²_2|1.3MB/s|GPTâº|YT-CN|NF|D+|GM|26%|KeepSucced
    server: gtm1.ktmwan.net
    port: 12890
    uuid: 0d36b2c4-a554-4e54-bd53-1975fc960ba6
    alterId: 0
    network: ws
    cipher: auto
    servername: gtm1.ktmwan.net
    ws-opts:
      path: /
      headers:
        Host: gtm1.ktmwan.net
    tls: true
  - type: hysteria
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_1
    server: 51.159.226.1
    port: 49003
    protocol: udp
    alpn:
      - '["h3"]'
  - type: vmess
    name: ğŸ‡»ğŸ‡³VNÂ²_1|5.8MB/s|GPTâº|YT-CN|NF|KeepSucced
    server: gtm1.ktmwan.net
    port: 12891
    uuid: 0d36b2c4-a554-4e54-bd53-1975fc960ba6
    alterId: 0
    network: ws
    cipher: auto
    servername: gtm1.ktmwan.net
    ws-opts:
      path: /
      headers:
        Host: gtm1.ktmwan.net
    tls: true
  - type: vmess
    name: ğŸ‡¦ğŸ‡ºAUÂ²_1|3.7MB/s|GPTâº|YT|NF|GM|KeepHistory
    server: gtm1.ktmwan.net
    port: 12889
    uuid: 0d36b2c4-a554-4e54-bd53-1975fc960ba6
    alterId: 0
    network: ws
    cipher: auto
    servername: gtm1.ktmwan.net
    ws-opts:
      path: /
      headers:
        Host: gtm1.ktmwan.net
    tls: true
  - type: vmess
    name: ğŸ‡«ğŸ‡·FRÂ²_3|1.1MB/s|GPTâº|NF|0%|KeepSucced
    server: gtm1.ktmwan.net
    port: 12886
    uuid: 0d36b2c4-a554-4e54-bd53-1975fc960ba6
    alterId: 0
    network: ws
    cipher: auto
    servername: gtm1.ktmwan.net
    ws-opts:
      path: /
      headers:
        Host: gtm1.ktmwan.net
    tls: true
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_1_1
    server: www.speedtest.net
    port: 80
    uuid: 877a6d5c-c78e-4ebe-8ad8-81ce2cde3f3c
    network: ws
    servername: websocket.network.www.speedtest.net.flutter.dev.russia.pyt.digitalcity5.xyz.
    encryption: none
    ws-opts:
      path: /@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy
      headers:
        Host: websocket.network.www.speedtest.net.flutter.dev.russia.pyt.digitalcity5.xyz.
  - type: vmess
    name: ğŸ‡¨ğŸ‡³ CN_31
    server: gtm1.ktmwan.net
    port: 12883
    uuid: 0d36b2c4-a554-4e54-bd53-1975fc960ba6
    alterId: 0
    network: ws
    cipher: auto
    servername: v1.pstatp.com
    ws-opts:
      path: /
      headers:
        Host: v1.pstatp.com
    tls: true
  - type: hysteria2
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_2
    server: 67e01b04-t3dk00-tcm6ys-deip.la.shifen.uk
    port: 1743
    password: 7a2512b4-09ee-11f0-8d46-f23c9313b177
    sni: 67e01b04-t3dk00-tcm6ys-deip.la.shifen.uk
  - type: hysteria2
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_3
    server: 61f04f6d-t4v9c0-t5amrp-b4pt.la.shifen.uk
    port: 1743
    password: be8cc8f6-0c6a-11f0-a5a3-f23c93141fad
    skip-cert-verify: true
    sni: 61f04f6d-t4v9c0-t5amrp-b4pt.la.shifen.uk
  - type: vmess
    name: ğŸ‡«ğŸ‡·FRÂ²_2|1.4MB/s|GPTâº|YT-DE|NF|45%|KeepSucced
    server: gtm1.ktmwan.net
    port: 12898
    uuid: 0d36b2c4-a554-4e54-bd53-1975fc960ba6
    alterId: 0
    network: ws
    cipher: auto
    servername: gtm1.ktmwan.net
    ws-opts:
      path: /
      headers:
        Host: gtm1.ktmwan.net
    tls: true
  - type: vmess
    name: ğŸ‡¨ğŸ‡¦CAÂ²_3|3.6MB/s|GPTâº|YT|NF|23%|KeepHistory
    server: gtm1.ktmwan.net
    port: 12897
    uuid: 0d36b2c4-a554-4e54-bd53-1975fc960ba6
    alterId: 0
    network: ws
    cipher: auto
    servername: gtm1.ktmwan.net
    ws-opts:
      path: /
      headers:
        Host: gtm1.ktmwan.net
    tls: true
  - type: hysteria2
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_4
    server: 3d2c11f1-t52o00-tdw2ye-2gok.la.shifen.uk
    port: 1743
    password: 17cdeb6c-f046-11ee-bdac-f23c93141fad
    sni: 3d2c11f1-t52o00-tdw2ye-2gok.la.shifen.uk
  - type: hysteria2
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_5
    server: 98f4acfe-t4un40-tdini3-cdfn.la.shifen.uk
    port: 1743
    password: 94931862-1484-11f0-9ab7-f23c95b6f51d
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_6
    server: 172.67.162.50
    port: 443
    uuid: e4cbe8b8-37db-4aaa-8469-b84f34c51ebc
    network: ws
    servername: eEedFR5.7777155.Xyz
    tls: true
    encryption: none
    ws-opts:
      path: /6OWLjRc26b0nHYr5hYXD
      headers:
        Host: eEedFR5.7777155.Xyz
  - type: hysteria2
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_7
    server: 47cc555c-t55r40-tdtaxw-au6.la.shifen.uk
    port: 1743
    ports: 20000-50000
    password: 1b609740-eec2-11ef-8543-f23c93136cb3
    sni: 47cc555c-t55r40-tdtaxw-au6.la.shifen.uk
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_8
    server: delilah.ns.cloudflare.com
    port: 443
    uuid: 8b69546f-56eb-4fb7-a3a9-642a0c259f3d
    network: ws
    servername: 638980501945994339.insight-amshb.com
    tls: true
    encryption: none
    ws-opts:
      path: /mdtduaws
      headers:
        Host: 638980501945994339.insight-amshb.com
  - type: hysteria2
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_9
    server: 68f48101-t4teo0-t5waci-4550.la.shifen.uk
    port: 1743
    password: 6286105c-fb6d-11ef-be96-f23c93136cb3
    sni: 68f48101-t4teo0-t5waci-4550.la.shifen.uk
  - type: hysteria2
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_10
    server: 37a48ffc-t4whs0-t5a0jp-b4pt.la.shifen.uk
    port: 1743
    ports: 20000-50000
    password: be8cc8f6-0c6a-11f0-a5a3-f23c93141fad
    sni: 37a48ffc-t4whs0-t5a0jp-b4pt.la.shifen.uk
  - type: hysteria2
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_11
    server: d48dac10-t4v9c0-tdtx5w-au6.la.shifen.uk
    port: 1743
    password: 1b609740-eec2-11ef-8543-f23c93136cb3
    sni: d48dac10-t4v9c0-tdtx5w-au6.la.shifen.uk
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_12
    server: cosmin.ns.cloudflare.com
    port: 443
    uuid: a9e3ba2a-8aa0-4796-8d1a-a1604e6398d5
    network: ws
    servername: 638980501945990220.insight-amshb.com
    tls: true
    encryption: none
    ws-opts:
      path: /plamruws
      headers:
        Host: 638980501945990220.insight-amshb.com
  - type: hysteria2
    name: ğŸ‡·ğŸ‡º_RU_ä¿„ç½—æ–¯_1
    server: ny.jueduibupao.top
    port: 50001
    password: 3807d049-edf7-47f2-af91-b601f89caf88
    skip-cert-verify: true
    sni: ny.jueduibupao.top
  - type: hysteria2
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_13
    server: dcc40639-t3cxs0-tcj7b6-d70y.la.shifen.uk
    port: 1743
    password: 537d7098-fdbe-11ef-8ebc-f23c93141fad
    sni: dcc40639-t3cxs0-tcj7b6-d70y.la.shifen.uk
  - type: hysteria2
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_14
    server: 227fd503-t4ssg0-t5vo4i-4550.la.shifen.uk
    port: 1743
    password: 6286105c-fb6d-11ef-be96-f23c93136cb3
    sni: 227fd503-t4ssg0-t5vo4i-4550.la.shifen.uk
