# åˆ›å»ºè€…ï¼šç”¨æˆ·è‡ªå®šä¹‰èŠ‚ç‚¹é…ç½®
# åˆ›å»ºæ—¶é—´ï¼š2025-09-27 08:00:00

# å•èŠ‚ç‚¹é…ç½®
proxies:
  - name: ðŸ‡§ðŸ‡·_BR_å·´è¥¿->ðŸ‡ºðŸ‡¸_US_ç¾Žå›½
    type: vmess
    server: 188.114.98.0
    port: 8080
    uuid: nasnet
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    network: ws
    ws-opts:
      path: /nasnet/cdn
      headers:
        Host: nasnet-162191099.sharghdaily.co
  - name: ðŸ‡¨ðŸ‡³_CN_ä¸­å›½
    type: vless
    server: 156.224.78.8
    port: 10001
    uuid: 9c79aceb-4649-44ea-9698-b5e9ecf6d6da
    servername: www.icloud.com
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    reality-opts:
      public-key: D_kMOsg1KCtT0tudPFVDXGuEcSqZGtUYqBB-BiIxmls
      short-id: f7223dab
  - name: ðŸ‡·ðŸ‡º_RU_ä¿„ç½—æ–¯
    type: vless
    server: 87.239.111.227
    port: 443
    uuid: 895f94cb-5567-4731-bc2c-2f89a54bafe4
    network: grpc
    servername: m.vk.ru
    tls: true
    client-fingerprint: chrome
    grpc-opts:
      grpc-service-name: grpc
    reality-opts:
      public-key: kz54nOxv8IOst-C_GQO5cf6106be0UakNbCEXiDuhHA
      short-id: 3863adb3
  - name: æœªçŸ¥
    type: ss
    server: 103.186.155.231
    port: 38388
    cipher: aes-256-cfb
    password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  - name: ðŸ‡·ðŸ‡º_RU_ä¿„ç½—æ–¯->ðŸ‡¨ðŸ‡¿_CZ_æ·å…‹
    type: vless
    server: 89.169.128.105
    port: 8443
    uuid: 3c5c4ccc-b502-42cb-8c42-cfa714db4767
    servername: yandex.ru
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    reality-opts:
      public-key: 7zd9mJilgjOrg_ohtw23Vmio-pdnYqeP_r-kiWt87Cg
      short-id: f4b4a6365558ea2e
  - name: ðŸ‡·ðŸ‡º_RU_ä¿„ç½—æ–¯_1
    type: vless
    server: 78.153.139.68
    port: 8443
    uuid: fd8972d7-cf5e-11f0-9970-45e1d80c4039
    servername: images.apple.com
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    reality-opts:
      public-key: pekfYPV5U8EjfQ4_zS5c6I2NnOZ2jUlyMGAWa4FWPF4
      short-id: 58c512b4422e2517
  - name: ðŸ‡®ðŸ‡±_IL_ä»¥è‰²åˆ—
    type: vmess
    server: 149.88.95.94
    port: 40741
    uuid: 1b8a751b-4909-4fec-f019-907d92e6c47f
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    network: none
  - name: ðŸ‡¨ðŸ‡³_CN_ä¸­å›½_1
    type: vless
    server: 2.hk.1.cdn-bilibili.cn
    port: 443
    uuid: fcfc091d-81a4-40b7-cbdc-8eb7683617a4
    servername: www.icloud.com
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: safari
    reality-opts:
      public-key: 4cfuj5otn8-uhPUe23OhB6KY8I42AxxJNt4lWIpg_AU
  - name: æœªçŸ¥_1
    type: ss
    server: 103.186.154.4
    port: 38388
    cipher: aes-256-cfb
    password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  - name: æœªçŸ¥_2
    type: ss
    server: 103.186.154.33
    port: 38388
    cipher: aes-256-cfb
    password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  - name: æœªçŸ¥_3
    type: ss
    server: 103.186.155.111
    port: 38388
    cipher: aes-256-cfb
    password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  - name: æœªçŸ¥_4
    type: ss
    server: 103.186.154.79
    port: 38388
    cipher: aes-256-cfb
    password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  - name: ðŸ‡ºðŸ‡¸_US_ç¾Žå›½->ðŸ‡³ðŸ‡¿_NZ_æ–°è¥¿å…°
    type: vless
    server: 69.84.182.13
    port: 443
    uuid: da793913-33ef-45c0-806d-f23644c555f2
    network: ws
    servername: jp1-jp1.aiopen.sbs
    tls: true
    client-fingerprint: chrome
    ws-opts:
      path: /kbjc/jp1
      headers:
        Host: jp1-jp1.aiopen.sbs
  - name: æœªçŸ¥_5
    type: ss
    server: 103.186.154.12
    port: 38388
    cipher: aes-256-cfb
    password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  - name: æœªçŸ¥_6
    type: ss
    server: 103.186.154.239
    port: 38388
    cipher: aes-256-cfb
    password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
