# åˆ›å»ºè€…ï¼šç”¨æˆ·è‡ªå®šä¹‰èŠ‚ç‚¹é…ç½®
# åˆ›å»ºæ—¶é—´ï¼š2025-09-27 08:00:00

# å•èŠ‚ç‚¹é…ç½®
proxies:
  - name: ğŸ‡©ğŸ‡ª_DE_å¾·å›½
    type: vless
    server: 91.211.114.143
    port: 8443
    uuid: f4fec1b0-a67e-4967-b9ea-0bd832b57a4d
    servername: sun6-21.userapi.com
    tls: true
    client-fingerprint: chrome
    reality-opts:
      public-key: upDCW94g-pSYQrmXvOrTVYlwBUrSKhYFF9QwrqObdVo
      short-id: 3ca620a7ed5f3196
  - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½
    type: vless
    server: pol-0001-xr.packet-drop-society.net
    port: 443
    uuid: ba77276e-9939-4c6c-a73e-90e02b6faf13
    servername: hls-svod.itunes.apple.com
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    reality-opts:
      public-key: llaiqC-oIhL_bjc236FPq26LSn7IVhIa4cIC6OVytws
      short-id: "31"
  - name: ğŸ‡³ğŸ‡±_NL_è·å…°
    type: vless
    server: pol.fasti.win
    port: 443
    uuid: 2b76609f-2132-42ac-a8fd-89635f73c85a
    servername: pl.fasti.win
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    reality-opts:
      public-key: -YTGWg5DjsLDyaDfr1D83kiUK22LVcrK3yC53lqqigs
      short-id: feedbacc
  - name: ğŸ‡®ğŸ‡±_IL_ä»¥è‰²åˆ—
    type: vless
    server: 31.133.100.249
    port: 443
    uuid: 55caaee8-4efd-40a5-8578-3edc39e0aff1
    servername: www.microsoft.com
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: random
    reality-opts:
      public-key: 7Ch1IcMY1Cq1d5ZK71mNRZ2kI8MLjRMFqN4Rmmp913M
      short-id: 2ff45b6c5e99c32e
  - name: ğŸ‡·ğŸ‡º_RU_ä¿„ç½—æ–¯->ğŸ‡°ğŸ‡¿_KZ_å“ˆè¨å…‹æ–¯å¦
    type: vless
    server: 194.110.55.46
    port: 443
    uuid: ba77276e-9939-4c6c-a73e-90e02b6faf13
    servername: hls-svod.itunes.apple.com
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    reality-opts:
      public-key: llaiqC-oIhL_bjc236FPq26LSn7IVhIa4cIC6OVytws
      short-id: "31"
  - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½->ğŸ³ï¸_unKnow_æœªçŸ¥
    type: vless
    server: 104.17.163.123
    port: 443
    uuid: 5280a5f7-0b5c-42b0-bf07-bd17b21fae60
    network: ws
    servername: klkl.sep-vpn.site
    tls: true
    client-fingerprint: chrome
    ws-opts:
      path: /
      headers:
        Host: klkl.sep-vpn.site
  - name: ğŸ‡·ğŸ‡º_RU_ä¿„ç½—æ–¯
    type: vless
    server: 78.153.139.68
    port: 8443
    uuid: fd8972d7-cf5e-11f0-9970-45e1d80c4039
    network: raw
    servername: images.apple.com
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: random
    reality-opts:
      public-key: pekfYPV5U8EjfQ4_zS5c6I2NnOZ2jUlyMGAWa4FWPF4
      short-id: 58c512b4422e2517
  - name: ğŸ‡ºğŸ‡¦_UA_ä¹Œå…‹å…°
    type: vless
    server: fra-0001-xr.packet-drop-society.net
    port: 443
    uuid: ba77276e-9939-4c6c-a73e-90e02b6faf13
    servername: hls-svod.itunes.apple.com
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    reality-opts:
      public-key: llaiqC-oIhL_bjc236FPq26LSn7IVhIa4cIC6OVytws
      short-id: "31"
  - name: ğŸ‡«ğŸ‡·_FR_æ³•å›½
    type: vless
    server: iar.blackhoster.com
    port: 350
    uuid: 79a48cba-4a44-4a5c-bfa9-64a53379df2c
    servername: excoino.com
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    reality-opts:
      public-key: YWfCdTnr4FAOMYTY2dLrMtQUokyxOGpPhYEEszPj20E
      short-id: fd1dff03520d8f56
  - name: ğŸ‡¬ğŸ‡§_GB_è‹±å›½->ğŸ‡¯ğŸ‡µ_JP_æ—¥æœ¬
    type: vless
    server: 146.185.241.64
    port: 7443
    uuid: c7f067ad-044c-407e-b1d2-711902903ac0
    servername: eh.vk.com
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    reality-opts:
      public-key: SyjVadnQbWChjFZ6xqq4LkXRWHrUy65OYgHwEP7o6Xw
      short-id: "111111"
  - name: ğŸ‡¸ğŸ‡¬_SG_æ–°åŠ å¡->ğŸ‡©ğŸ‡ª_DE_å¾·å›½
    type: vless
    server: ger2.panbehpanel.ir
    port: 443
    uuid: c33275fd-a4fa-470d-90e4-55da39d849a8
    servername: panbehpanel.ir
    tls: true
  - name: ğŸ‡·ğŸ‡º_RU_ä¿„ç½—æ–¯->ğŸ‡¨ğŸ‡¿_CZ_æ·å…‹
    type: vless
    server: 84.23.52.70
    port: 8443
    uuid: 0ff8dbfb-d7ee-4a19-b22d-b652a8b52e22
    servername: m.vk.ru
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    reality-opts:
      public-key: 7zd9mJilgjOrg_ohtw23Vmio-pdnYqeP_r-kiWt87Cg
      short-id: 8ba12e75110b7a9c
  - name: ğŸ‡·ğŸ‡º_RU_ä¿„ç½—æ–¯_1
    type: vless
    server: 79.133.180.45
    port: 443
    uuid: 6b1c3308-9bb4-45bc-8387-25c969a8c8f9
    servername: www.microsoft.com
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    reality-opts:
      public-key: 45ui5TpjfPf6HmRyT4M53XnR9tOXjpcLRLmaRyhlPiQ
      short-id: d7325e33
  - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½->ğŸ‡«ğŸ‡·_FR_æ³•å›½
    type: vless
    server: 104.18.32.47
    port: 80
    uuid: 1e35b4bf-b270-4c0b-918d-62746eedd2ad
    network: ws
    tls: false
    ws-opts:
      path: /?ed
      headers:
        Host: EveRLaSTinG-fiNANcE439p1sxXHY.SPORtLAND.CompanY.
  - name: ğŸ‡©ğŸ‡°_DK_ä¸¹éº¦
    type: vless
    server: 159.195.26.28
    port: 443
    uuid: 84f66368-8a37-468e-ae95-5622255fd4db
    servername: live.com
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    reality-opts:
      public-key: ckRcueERkPqqjZABwxqni_J_Nbb70Q6k5fEEUAjoImw
  - name: ğŸ‡¸ğŸ‡¨_SC_å¡èˆŒå°”
    type: vless
    server: nd.fasti.win
    port: 443
    uuid: 8db9aae9-1d66-4a34-8f35-42a7a34f269b
    servername: nd.fasti.win
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    reality-opts:
      public-key: XBBVeMURFu7jmYJ9MZwjEWgfQlGTnRs0B5So5Fy7jWs
      short-id: 992f3294e2336744
  - name: ğŸ‡³ğŸ‡±_NL_è·å…°_1
    type: vless
    server: ficdn15.suio.me
    port: 443
    uuid: a7a9f670-44c0-45a9-8047-69db0203c142
    servername: ficdn15.suio.me
    tls: true
    client-fingerprint: chrome
  - name: ğŸ‡·ğŸ‡º_RU_ä¿„ç½—æ–¯_2
    type: vless
    server: 176.125.240.166
    port: 443
    uuid: 002accb526534fcab24a72b0ea1cff59
    servername: apple.com
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: random
    reality-opts:
      public-key: GgiY38LjRI1hS1LKhdqvtJ5SDDO436GvihG-TzEI2XE
      short-id: aabbccdd
  - name: ğŸ‡³ğŸ‡±_NL_è·å…°->ğŸ‡ºğŸ‡¸_US_ç¾å›½
    type: vless
    server: 132.226.147.10
    port: 443
    uuid: b527363c-efb8-4a3f-9209-cdeb18349afd
    servername: musicstatus.tv.apple.com
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    reality-opts:
      public-key: OEZ3C-1OCSYBikqcWudtPP3PpQq2RAI7rFPxWoTCDSc
      short-id: bffe9292
  - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½->ğŸ‡³ğŸ‡±_NL_è·å…°
    type: vless
    server: 8.6.112.0
    port: 2053
    uuid: 48792731-6fc9-4415-8b51-6007825daf82
    network: ws
    servername: ir7.hnbyme.online
    tls: true
    client-fingerprint: chrome
    ws-opts:
      path: /
      headers:
        Host: ir7.hnbyme.online
  - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_1
    type: vmess
    server: 154.83.2.156
    port: 2086
    uuid: 92373ed1-78a8-4cbe-aa06-54af1edd0471
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    network: ws
    ws-opts:
      path: /
      headers:
        Host: v205.19740822.xyz
