# åˆ›å»ºè€…ï¼šç”¨æˆ·è‡ªå®šä¹‰èŠ‚ç‚¹é…ç½®
# åˆ›å»ºæ—¶é—´ï¼š2025-09-27 08:00:00

# å•èŠ‚ç‚¹é…ç½®
proxies:
 - name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½
   network: tcp
   password: adbac894-90b9-4913-b77e-a715a8d4ebc8
   port: 20021
   server: oss-cn-shanghai.letssepub.com
   sni: dingding-doc.com
   tls: true
   type: trojan
 - name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_1
   network: tcp
   port: 443
   server: 58.152.53.42
   sni: www.nintendogames.net
   type: trojan
 - name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_2
   network: tcp
   password: bca467b8c15211d189008a93c7519d3b
   port: 2283
   server: 117.172.176.24
   sni: www.nintendogames.net
   type: trojan
 - client-fingerprint: firefox
   flow: xtls-rprx-vision
   name: ğŸ‡ºğŸ‡¸_US_ç¾å›½
   network: tcp
   port: 36666
   reality-opts:
     public-key: cqCSxloJscJ3ZrNUlkSKkUFZ7SZ6vzQNszGolW_o7HY
     short-id: 6da03029
   server: hk3.cv1168.com
   servername: www.python.org
   tls: true
   type: vless
   uuid: aae56c24-7511-4526-9708-3fcbd804253c
 - name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_3
   network: tcp
   password: BxceQaOe
   port: 4556
   server: 36.151.192.242
   skip-cert-verify: true
   type: trojan
 - name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_4
   network: tcp
   password: BxceQaOe
   port: 194
   server: 36.151.192.242
   skip-cert-verify: true
   type: trojan
 - client-fingerprint: chrome
   name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_1
   network: ws
   port: 2053
   server: 199.34.230.114
   servername: om1.omidsuccess.uk
   tls: true
   type: vless
   uuid: b27e35a7-51f4-468e-8921-56a4901dd923
   ws-opts:
     headers:
       Host: om1.omidsuccess.uk
     path: /containers/de
 - client-fingerprint: chrome
   name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_2
   network: ws
   port: 443
   server: 172.66.47.63
   servername: aDD-1cV.pAGeS.Dev
   tls: true
   type: vless
   uuid: 2836c061-ea09-45e5-a98e-4ca478e744b0
   ws-opts:
     headers:
       Host: aDD-1cV.pAGeS.Dev
     path: /f2GYY0YixkpPeMtx/Y2RuLWIxMDAueG4tLWI2Z2FjLmV1Lm9yZw
 - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_3
   password: 16955d72-1794-11f0-a035-f23c95b6f51d
   port: 1743
   server: fecc1dc4-t4v9c0-t5ht86-dnss.la.shifen.uk
   type: hysteria2
 - alterId: 0
   cipher: auto
   name: å¾·å›½ V2CROSS.COM
   network: ws
   port: 80
   server: 77.37.33.67
   servername: google.whatsapp.snapp.torob.basalam.leoshopping77.ir.
   type: vmess
   uuid: d967ffca-de90-4daa-bd00-d527e5bae11f
   ws-opts:
     headers:
       Host: google.whatsapp.snapp.torob.basalam.leoshopping77.ir.
     path: /?BIA_TELEGRAM(@AZARBAYJAB1)TM(@AZARBAYJAB1)TM(@AZARBAYJAB1)TM(@AZARBAYJAB1)TM(@AZARBAYJAB1)TM(@AZARBAYJAB1)
 - client-fingerprint: chrome
   flow: xtls-rprx-vision
   name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_4
   network: tcp
   port: 17836
   server: usvless.yydzx.xyz
   servername: usvless.yydzx.xyz
   tls: true
   type: vless
   uuid: 4e084535-bd62-458b-84a2-a0dc57c957aa
 - alterId: 0
   cipher: auto
   name: ğŸ‡ºğŸ‡¸ ç¾å›½ CloudFlareèŠ‚ç‚¹
   network: ws
   port: 80
   server: 104.18.240.238
   servername: google.whatsapp.snapp.torob.basalam.leoshopping77.ir.
   type: vmess
   uuid: d967ffca-de90-4daa-bd00-d527e5bae11f
   ws-opts:
     headers:
       Host: google.whatsapp.snapp.torob.basalam.leoshopping77.ir.
     path: /?BIA_TELEGRAM (@AZARBAYJAB1) TM (@AZARBAYJAB1) TM (@AZARBAYJAB1) TM (@AZARBAYJAB1) TM (@AZARBAYJAB1) TM (@AZARBAYJAB1)
 - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_5
   password: 6286105c-fb6d-11ef-be96-f23c93136cb3
   port: 1743
   server: cc65f71a-t4v9c0-t5waci-4550.la.shifen.uk
   type: hysteria2
 - alterId: 0
   cipher: auto
   name: ğŸ‡ºğŸ‡¸ ç¾å›½ 454
   network: ws
   port: 80
   server: a4932bbe-005c-1509-7b27-51aa7b17a6fb.999161.xyz
   servername: a4932bbe-005c-1509-7b27-51aa7b17a6fb.999161.xyz
   type: vmess
   uuid: 34a7da0c-a43a-49b8-a8d0-64b43100090e
   ws-opts:
     headers:
       Host: a4932bbe-005c-1509-7b27-51aa7b17a6fb.999161.xyz
     path: /e7JS5ETJeA85VyjPCYXwETL
 - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_6
   password: 3c24bd4c-72a2-4036-93cf-6837e131d403
   port: 18785
   server: 192.238.232.130
   skip-cert-verify: true
   sni: www.bing.com
   type: hysteria2
 - encryption: none
   name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_7
   network: ws
   port: 80
   server: 104.18.255.7
   servername: vpn13.sakeva2327.workers.dev
   type: vless
   uuid: ac90a749-1b0d-4978-a767-ab07b0f3f98f
   ws-opts:
     headers:
       Host: vpn13.sakeva2327.workers.dev
     path: /
 - fingerprint: random
   name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_8
   network: ws
   password: trojan
   port: 443
   server: ip.sb
   sni: nixian.pages.dev
   tls: true
   type: trojan
   ws-opts:
     headers:
       Host: nixian.pages.dev
     path: /?ed=2560/?Join-sho--Telegram--VITUREY-Join-sho--Telegram--VITUREY-Join-sho--Telegram--VITUREY-Join-sho--Telegram--VITUREY-Join-sho--Telegram--VITUREY-Join-sho--Telegram--VITUREY-Join-sho--Telegram--VITUREY-Join-sho--Telegram--VITUREY-Join-sho--Telegram--VITUREY-Join-sho--Telegram--VITUREY-Join-sho--Telegram--VITUREY-
 - alterId: 0
   cipher: auto
   name: ğŸ‡©ğŸ‡ª å¾·å›½ 33
   network: ws
   port: 80
   server: 141.101.121.250
   servername: google.whatsapp.snapp.torob.basalam.leoshopping77.ir.
   type: vmess
   uuid: d967ffca-de90-4daa-bd00-d527e5bae11f
   ws-opts:
     headers:
       Host: google.whatsapp.snapp.torob.basalam.leoshopping77.ir.
     path: /?BIA_TELEGRAM (@AZARBAYJAB1) TM (@AZARBAYJAB1) TM (@AZARBAYJAB1) TM (@AZARBAYJAB1) TM (@AZARBAYJAB1) TM (@AZARBAYJAB1)
 - alterId: 0
   cipher: auto
   name: DE_555fe_0004
   network: ws
   port: 80
   server: 77.37.33.108
   servername: google.whatsapp.snapp.torob.basalam.leoshopping77.ir.
   type: vmess
   uuid: d967ffca-de90-4daa-bd00-d527e5bae11f
   ws-opts:
     headers:
       Host: google.whatsapp.snapp.torob.basalam.leoshopping77.ir.
     path: /
 - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_9
   password: 7a2512b4-09ee-11f0-8d46-f23c9313b177
   port: 1743
   server: 67e01b04-t3dk00-tcm6ys-deip.la.shifen.uk
   type: hysteria2
 - name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_3_1
   network: tcp
   password: BxceQaOe
   port: 4492
   server: 36.150.215.236
   skip-cert-verify: true
   type: trojan
 - name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_5
   network: tcp
   password: bca467b8c15211d189008a93c7519d3b
   port: 1332
   server: 117.172.176.24
   sni: www.nintendogames.net
   type: trojan
 - name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_6
   network: tcp
   password: BxceQaOe
   port: 51825
   server: 36.150.215.197
   skip-cert-verify: true
   type: trojan
 - name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_7
   network: tcp
   password: BxceQaOe
   port: 53743
   server: 36.151.251.47
   skip-cert-verify: true
   type: trojan
 - client-fingerprint: chrome
   name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_1_1
   network: ws
   port: 443
   server: 69.84.182.18
   servername: cdn-node-oss-63.paofu.de
   tls: true
   type: vless
   uuid: a25ff90c-964c-485a-b72a-858864a27dc0
   ws-opts:
     headers:
       Host: cdn-node-oss-63.paofu.de
     path: /profile/sharenode
 - name: ğŸ‡®ğŸ‡·_IR_ä¼Šæœ—
   password: 70f44486-cda5-4750-9bf5-ca8826ee9bcc
   port: 11112
   server: us2.oxdtangx.top
   skip-cert-verify: true
   sni: us2.oxdtangx.top
   type: hysteria2
 - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_2_1
   password: be8cc8f6-0c6a-11f0-a5a3-f23c93141fad
   port: 1743
   server: 61f04f6d-t4v9c0-t5amrp-b4pt.la.shifen.uk
   type: hysteria2
 - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_4_1
   password: 712bdc36-24be-11ee-be53-f23c9313b177
   port: 1743
   server: fe1d6996-t4v9c0-tcl9of-5fdt.la.shifen.uk
   type: hysteria2
 - name: ğŸ‡®ğŸ‡·_IR_ä¼Šæœ—_1
   password: e2c4b8ed-5968-4c23-aeb5-60551c09c9a6
   port: 2222
   server: mg1.xinlancloud.top
   skip-cert-verify: true
   sni: mg1.xinlancloud.top
   type: hysteria2
 - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_5_1
   password: 1b609740-eec2-11ef-8543-f23c93136cb3
   port: 1743
   server: eb8d3417-t4teo0-tdtx5w-au6.la.shifen.uk
   type: hysteria2
 - alterId: 2
   cipher: auto
   name: ğŸ‡®ğŸ‡¹ æ„å¤§åˆ© 01
   network: tcp
   port: 30805
   server: v5.heduian.link
   servername: v5.heduian.link
   type: vmess
   uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
 - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_6_1
   password: 537d7098-fdbe-11ef-8ebc-f23c93141fad
   port: 1743
   server: dcc40639-t3cxs0-tcj7b6-d70y.la.shifen.uk
   type: hysteria2
 - name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_7_1
   password: bf47336b-1642-4db6-b1fe-8401e0f2405e
   port: 11112
   server: yg1.oxdtangx.top
   skip-cert-verify: true
   sni: yg1.oxdtangx.top
   type: hysteria2
 - client-fingerprint: chrome
   encryption: none
   flow: xtls-rprx-vision
   name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_8_1
   network: tcp
   port: 993
   reality-opts:
     public-key: GfTzhy59k9CXlAdF819OUVeBdrqIILaDIWa1bddjGnA
   server: 155.212.110.2
   servername: speed.cloudflare.com
   tls: true
   type: vless
   uuid: 40730d97-ffa7-1108-2c53-761516eb5fda
 - alterId: 0
   cipher: auto
   name: '%F0%9D%92%83%F0%9D%92%90%F0%9D%92%8D%F0%9D%92%83%F0%9D%92%90%F0%9D%92%8D%F0%9D%92%97%F0%9D%92%91%F0%9D%92%8F-%40bolbolservice'
   network: tcp
   port: 2060
   server: ksadk/23.korosh.shop
   type: vmess
   uuid: 1648bc92-d210-4d17-9174-710231d5b23e
 - cipher: chacha20-ietf
   name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_8
   password: asd123456
   port: 8388
   server: 103.149.183.154
   type: ss
 - alterId: 0
   cipher: auto
   name: AUğŸ‡¦ğŸ‡º | arda101.ardaserver.site-34167 | 275.19ms
   network: tcp
   port: 34167
   server: arda101.ardaserver.site
   type: vmess
   uuid: 571cd4a3-e2af-4bab-a6f5-3b5906afc111
 - name: ğŸ‡®ğŸ‡·_IR_ä¼Šæœ—_2
   password: 16877559-98a8-4f8b-906c-cecad0867c0d
   port: 54265
   server: banmabanmabanmabanmabanmabanma1.wanlidag.top
   skip-cert-verify: true
   sni: banmabanmabanmabanmabanmabanma1.wanlidag.top
   type: hysteria2
 - alterId: 2
   cipher: auto
   name: ğŸ‡­ğŸ‡° HK_89
   network: ws
   port: 80
   server: 77e1818c-t13gg0-t5fh9u-1uni.hk3.p5pv.com
   servername: broadcastlv.chat.bilibili.com
   type: vmess
   uuid: adbd0a82-3336-11ed-bd7c-f23c913c8d2b
   ws-opts:
     headers:
       Host: broadcastlv.chat.bilibili.com
     path: /
 - alterId: 2
   cipher: auto
   name: ğŸ‡­ğŸ‡° HK_324
   network: ws
   port: 80
   server: 10cd2f16-sv2sg0-t7hu58-1q1la.hk3.p5pv.com
   servername: broadcastlv.chat.bilibili.com
   type: vmess
   uuid: 25b46954-9a33-11ee-8b86-f23c91cfbbc9
   ws-opts:
     headers:
       Host: broadcastlv.chat.bilibili.com
     path: /
 - alterId: 2
   cipher: auto
   name: ğŸ‡­ğŸ‡°HK-219.77.235.50-1213
   network: ws
   port: 80
   server: 2e617951-sv2sg0-taj9mo-1tco3.hk3.p5pv.com
   servername: broadcastlv.chat.bilibili.com
   type: vmess
   uuid: e29de954-ea01-11ef-a271-f23c91cfbbc9
   ws-opts:
     headers:
       Host: broadcastlv.chat.bilibili.com
     path: /
 - alterId: 2
   cipher: auto
   name: ğŸ‡­ğŸ‡° HK_213
   network: ws
   port: 80
   server: a731a8b3-sv2sg0-sy1a0y-1iyov.hk3.p5pv.com
   servername: broadcastlv.chat.bilibili.com
   type: vmess
   uuid: 33629870-e57e-11ec-bb74-f23c9164ca5d
   ws-opts:
     headers:
       Host: broadcastlv.chat.bilibili.com
     path: /
 - alterId: 2
   cipher: auto
   name: ğŸ‡­ğŸ‡° HK_210
   network: ws
   port: 80
   server: 9d27188f-t00kg0-t9byd7-1jfvb.hk3.p5pv.com
   servername: broadcastlv.chat.bilibili.com
   type: vmess
   uuid: 06b2ac52-fcc6-11ec-bb74-f23c9164ca5d
   ws-opts:
     headers:
       Host: broadcastlv.chat.bilibili.com
     path: /
 - alterId: 2
   cipher: auto
   name: ğŸ‡­ğŸ‡° HK_231
   network: ws
   port: 80
   server: 360de725-sv4n40-t2y63q-1jk6u.hk3.p5pv.com
   servername: broadcastlv.chat.bilibili.com
   type: vmess
   uuid: 45bc25b2-1a10-11ed-91c0-f23c91cfbbc9
   ws-opts:
     headers:
       Host: broadcastlv.chat.bilibili.com
     path: /
 - alterId: 2
   cipher: auto
   name: ğŸ‡­ğŸ‡°HK-219.77.235.50-1223
   network: ws
   port: 80
   server: 7f346235-sv4n40-t76x2i-wj6v.hk3.p5pv.com
   servername: broadcastlv.chat.bilibili.com
   type: vmess
   uuid: 847c03b2-0a9d-11eb-a8bf-f23c91cfbbc9
   ws-opts:
     headers:
       Host: broadcastlv.chat.bilibili.com
     path: /
 - alterId: 2
   cipher: auto
   name: ğŸ‡­ğŸ‡°HK-219.77.235.50-1226
   network: ws
   port: 80
   server: 6dbaea45-sv0xs0-t9i7o2-1lt20.hk3.p5pv.com
   servername: broadcastlv.chat.bilibili.com
   type: vmess
   uuid: bf4ec108-f2b7-11ef-b654-f23c91cfbbc9
   ws-opts:
     headers:
       Host: broadcastlv.chat.bilibili.com
     path: /
 - alterId: 2
   cipher: auto
   name: ğŸ‡­ğŸ‡°HK-219.77.235.50-1215
   network: ws
   port: 80
   server: 00711758-sva740-tbrhck-1thqb.hk3.p5pv.com
   servername: broadcastlv.chat.bilibili.com
   type: vmess
   uuid: 4f4c6876-fcf6-11ef-94aa-f23c913c8d2b
   ws-opts:
     headers:
       Host: broadcastlv.chat.bilibili.com
     path: /
 - alterId: 2
   cipher: auto
   name: ğŸ‡­ğŸ‡° HK_72
   network: ws
   port: 80
   server: d5dc60aa-t0kxs0-t1nwsn-1la2q.hk3.p5pv.com
   servername: broadcastlv.chat.bilibili.com
   type: vmess
   uuid: 431026c8-7397-11ed-a8bf-f23c91cfbbc9
   ws-opts:
     headers:
       Host: broadcastlv.chat.bilibili.com
     path: /
 - alterId: 2
   cipher: auto
   name: ğŸ‡­ğŸ‡° HK_86
   network: ws
   port: 80
   server: f0364aea-t13gg0-t1rksu-1ssud.hk3.p5pv.com
   servername: broadcastlv.chat.bilibili.com
   type: vmess
   uuid: e6aa39b6-f0b5-11ef-bca1-f23c91cfbbc9
   ws-opts:
     headers:
       Host: broadcastlv.chat.bilibili.com
     path: /
 - alterId: 2
   cipher: auto
   name: ğŸ‡­ğŸ‡°HK-219.77.235.50-1220
   network: ws
   port: 80
   server: 4c2c02b9-sv2sg0-sv75lj-1swf9.hk3.p5pv.com
   servername: broadcastlv.chat.bilibili.com
   type: vmess
   uuid: 2bb1edc8-fa5d-11ef-9dd9-f23c9164ca5d
   ws-opts:
     headers:
       Host: broadcastlv.chat.bilibili.com
     path: /
 - alterId: 2
   cipher: auto
   name: ğŸ‡­ğŸ‡°HK-219.77.235.50-1224
   network: ws
   port: 80
   server: 6bdf8f31-sv2sg0-tdh9w7-ahsb.hk3.p5pv.com
   servername: broadcastlv.chat.bilibili.com
   type: vmess
   uuid: 2e42c1ee-aaaa-11ec-bb74-f23c9164ca5d
   ws-opts:
     headers:
       Host: broadcastlv.chat.bilibili.com
     path: /
 - alterId: 2
   cipher: auto
   name: ğŸ‡­ğŸ‡° HK_83
   network: ws
   port: 80
   server: 64309899-t15b40-t2c3sq-1spnr.hk3.p5pv.com
   servername: broadcastlv.chat.bilibili.com
   type: vmess
   uuid: 127e3f92-f714-11ef-bbb0-f23c91cfbbc9
   ws-opts:
     headers:
       Host: broadcastlv.chat.bilibili.com
     path: /
 - cipher: chacha20-ietf-poly1305
   name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_1_1
   password: 014e90df-a3ee-4654-a9f6-d118e02dd02a
   port: 41047
   server: sl.fgmcx.top
   type: ss
 - alterId: 2
   cipher: auto
   name: ğŸ‡­ğŸ‡°HK-219.77.235.50-1229
   network: ws
   port: 80
   server: dfed4efb-t4n8g0-t636g9-luwe.hk3.p5pv.com
   servername: broadcastlv.chat.bilibili.com
   type: vmess
   uuid: a2b0fd2b-716f-0df8-d4e2-03a1c00e5f1a
   ws-opts:
     headers:
       Host: broadcastlv.chat.bilibili.com
     path: /
 - alterId: 2
   cipher: auto
   name: ğŸ‡­ğŸ‡°HK-219.77.235.50-1214
   network: ws
   port: 80
   server: 1dd7778a-sv4n40-szxh9w-46gc.hk3.p5pv.com
   servername: broadcastlv.chat.bilibili.com
   type: vmess
   uuid: 225d1cca-d744-11ef-b790-f23c91cfbbc9
   ws-opts:
     headers:
       Host: broadcastlv.chat.bilibili.com
     path: /
 - alterId: 2
   cipher: auto
   name: ğŸ‡­ğŸ‡° HK_108
   network: ws
   port: 80
   server: 45c56923-sucv40-tcop2n-tl32.hk3.p5pv.com
   servername: broadcastlv.chat.bilibili.com
   type: vmess
   uuid: 5c02ab88-7b9c-11ea-8fc9-f23c913c8d2b
   ws-opts:
     headers:
       Host: broadcastlv.chat.bilibili.com
     path: /
 - alterId: 2
   cipher: auto
   name: ğŸ‡­ğŸ‡° HK_171
   network: ws
   port: 80
   server: b8ffcda3-sv2sg0-sv37gm-81nv.hk3.p5pv.com
   servername: broadcastlv.chat.bilibili.com
   type: vmess
   uuid: 47e91fb6-25b8-df52-bc18-3cdc8548192f
   ws-opts:
     headers:
       Host: broadcastlv.chat.bilibili.com
     path: /
 
