# åˆ›å»ºè€…ï¼šç”¨æˆ·è‡ªå®šä¹‰èŠ‚ç‚¹é…ç½®
# åˆ›å»ºæ—¶é—´ï¼š2025-09-27 08:00:00

# è®¢é˜…èŠ‚ç‚¹é…ç½®
proxy-providers:
  # é•¿é£Žæœºåœºè®¢é˜…
  Airport-changfeng:
    url: "https://git.io/emzclash"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ðŸš€ é»˜è®¤ä»£ç†

# å•èŠ‚ç‚¹é…ç½®
proxies:
- name: "ðŸ‡¨ðŸ‡³_CN_ä¸­å›½_1"
  type: "vmess"
  server: "v29.heduian.link"
  port: 30829
  sni: ""
  uuid: "cbb3f877-d1fb-344c-87a9-d153bffd5484"
  cipher: "auto"
  network: "ws"
  skip-cert-verify: true
  ws-opts:
    path: "/oooo"
    headers:
      host: "ocbc.com"
  alterId: 2
- name: "ðŸ‡ºðŸ‡¸_US_ç¾Žå›½"
  type: "trojan"
  server: "uk-03.allhubb.info"
  port: 8443
  password: "1ce1df7962f71c6f"
- name: "æœªçŸ¥"
  type: "ss"
  server: "103.186.154.70"
  port: 38388
  cipher: "aes-256-cfb"
  password: "Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV"
- name: "ðŸ‡¬ðŸ‡§_GB_è‹±å›½"
  type: "ss"
  server: "62.100.205.48"
  port: 989
  cipher: "aes-256-cfb"
  password: "f8f7aCzcPKbsF8p3"
- name: "æœªçŸ¥_1"
  type: "ss"
  server: "103.186.154.230"
  port: 38388
  cipher: "aes-256-cfb"
  password: "Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV"
- name: "ðŸ‡¸ðŸ‡°_SK_æ–¯æ´›ä¼å…‹->ðŸ‡·ðŸ‡º_RU_ä¿„ç½—æ–¯"
  type: "ss"
  server: "156.146.40.194"
  port: 989
  cipher: "aes-256-cfb"
  password: "f8f7aCzcPKbsF8p3"
- name: "ðŸ‡¸ðŸ‡ª_SE_ç‘žå…¸"
  type: "ss"
  server: "192.71.166.100"
  port: 989
  cipher: "aes-256-cfb"
  password: "f8f7aCzcPKbsF8p3"
