# åˆ›å»ºè€…ï¼šç”¨æˆ·è‡ªå®šä¹‰èŠ‚ç‚¹é…ç½®
# åˆ›å»ºæ—¶é—´ï¼š2025-09-27 08:00:00

# å•èŠ‚ç‚¹é…ç½®
proxies:
  - type: vless
    name: ğŸ‡°ğŸ‡·_KR_éŸ©å›½
    server: 59.2.75.64
    port: 50001
    uuid: 6923b959-c65f-764c-b072-94711382d716
    network: ws
    servername: s2.sni565.netlib.re
    tls: true
    encryption: none
    ws-opts:
      path: /proxyip=tw.sni2025.netlib.re
      headers:
        Host: s2.sni565.netlib.re
    client-fingerprint: random
    alpn:
      - h3
  - type: vless
    name: ğŸ‡¦ğŸ‡º_AU_æ¾³å¤§åˆ©äºš
    server: 43.161.227.251
    port: 60006
    uuid: 69228a95-e9cb-b1ff-40d2-7315d9d4b9b7
    network: ws
    servername: s3.sni565.netlib.re
    tls: true
    encryption: none
    ws-opts:
      path: /proxyip=tw.sni2025.netlib.re
      headers:
        Host: s3.sni565.netlib.re
    client-fingerprint: chrome
    alpn:
      - h3
  - type: vless
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½
    server: 220.128.110.108
    port: 43
    uuid: 69228a95-e9cb-b1ff-40d2-7315d9d4b9b7
    network: ws
    servername: s3.sni565.netlib.re
    tls: true
    encryption: none
    ws-opts:
      path: /proxyip=tw.sni2025.netlib.re
      headers:
        Host: s3.sni565.netlib.re
    client-fingerprint: chrome
    alpn:
      - h3
  - type: vless
    name: ğŸ‡¦ğŸ‡º_AU_æ¾³å¤§åˆ©äºš_1
    server: 43.161.227.251
    port: 60007
    uuid: 69228a95-e9cb-b1ff-40d2-7315d9d4b9b7
    network: ws
    servername: s3.sni565.netlib.re
    tls: true
    encryption: none
    ws-opts:
      path: /proxyip=tw.sni2025.netlib.re
      headers:
        Host: s3.sni565.netlib.re
    client-fingerprint: chrome
    alpn:
      - h3
  - type: vmess
    name: ã€æœºåœºæ¨èï¼šhttps://a0a.xyz/ã€‘45
    server: 144.48.180.187
    port: 30812
    uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
    alterId: 0
    network: tcp
    cipher: auto
  - type: vless
    name: ğŸ‡°ğŸ‡·_KR_éŸ©å›½_1
    server: 119.64.242.60
    port: 60002
    uuid: 69228a95-e9cb-b1ff-40d2-7315d9d4b9b7
    network: ws
    servername: s3.sni565.netlib.re
    tls: true
    encryption: none
    ws-opts:
      path: /proxyip=tw.sni2025.netlib.re
      headers:
        Host: s3.sni565.netlib.re
    client-fingerprint: chrome
    alpn:
      - h3
  - type: vless
    name: ğŸ‡¬ğŸ‡§_GB_è‹±å›½
    server: 83.229.123.87
    port: 443
    uuid: 6923b959-c65f-764c-b072-94711382d716
    network: ws
    servername: s2.sni565.netlib.re
    tls: true
    encryption: none
    ws-opts:
      path: /proxyip=tw.sni2025.netlib.re
      headers:
        Host: s2.sni565.netlib.re
    client-fingerprint: chrome
    alpn:
      - h3
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½
    server: 68.64.176.135
    port: 443
    uuid: 5aba5b77-48eb-4ae2-b60d-5bfee7ac169e
    network: ws
    servername: kuangbao.xiejiang.dpdns.org
    tls: true
    ws-opts:
      path: /?ed=2560
      headers:
        Host: kuangbao.xiejiang.dpdns.org
    client-fingerprint: random
    alpn:
      - h3
  - type: vless
    name: ğŸ‡·ğŸ‡º_RU_ä¿„ç½—æ–¯
    server: 193.124.18.13
    port: 443
    uuid: 5aba5b77-48eb-4ae2-b60d-5bfee7ac169e
    network: ws
    servername: kuangbao.xiejiang.dpdns.org
    tls: true
    ws-opts:
      path: /?ed=2560
      headers:
        Host: kuangbao.xiejiang.dpdns.org
  - type: vless
    name: ğŸ‡¨ğŸ‡­_CH_ç‘å£«
    server: 64.110.104.30
    port: 443
    uuid: 6923b959-c65f-764c-b072-94711382d716
    network: ws
    servername: s2.sni565.netlib.re
    tls: true
    encryption: none
    ws-opts:
      path: /proxyip=tw.sni2025.netlib.re
      headers:
        Host: s2.sni565.netlib.re
    client-fingerprint: random
    alpn:
      - h3
  - type: vmess
    name: ğŸ‡³ğŸ‡± è·å…° 05
    server: v30.hdacd.com
    port: 30830
    uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
    alterId: 0
    network: tcp
    cipher: auto
    servername: v30.hdacd.com
  - type: vmess
    name: ğŸ‡ºğŸ‡¸USÂ²_3|1.1MB/s|54%|GPTâº|TK-GB|NF|X|KeepHistory
    server: v36.hdacd.com
    port: 30836
    uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
    alterId: 2
    network: tcp
    cipher: auto
  - type: trojan
    name: ğŸ‡°ğŸ‡·_KR_éŸ©å›½_2
    server: hk3.t.sgateway.link
    port: 5223
    password: Q9gofGxinwLv0TfDfdKmdttdPGxrhKQS
    network: tcp
    sni: pod-hk-z1.psusercontent.com
  - type: vmess
    name: ğŸ‡©ğŸ‡ª å¾·å›½ 24
    server: v33.hdacd.com
    port: 30833
    uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
    alterId: 2
    network: tcp
    cipher: auto
    servername: v33.hdacd.com
  - type: ss
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_1
    server: 3.76.39.215
    port: 443
    cipher: aes-256-cfb
    password: amazonskr05
