# åˆ›å»ºè€…ï¼šç”¨æˆ·è‡ªå®šä¹‰èŠ‚ç‚¹é…ç½®
# åˆ›å»ºæ—¶é—´ï¼š2025-09-27 08:00:00

# å•èŠ‚ç‚¹é…ç½®
proxies:
  - type: hysteria
    name: ğŸ‡«ğŸ‡·_FR_æ³•å›½
    server: 62.210.196.68
    port: 26691
    auth-str: dongtaiwang.com
    protocol: udp
    sni: apple.com
    up: 11 Mbps
    down: 55 Mbps
    skip-cert-verify: true
    alpn:
      - h3
  - type: hysteria
    name: ğŸ‡«ğŸ‡·_FR_æ³•å›½_1
    server: 62.210.10.186
    port: 50011
    auth-str: dongtaiwang.com
    protocol: udp
    sni: apple.com
    up: 11 Mbps
    down: 55 Mbps
    skip-cert-verify: true
    alpn:
      - h3
  - type: hysteria
    name: ğŸ‡«ğŸ‡·_FR_æ³•å›½_2
    server: 62.210.10.186
    port: 35511
    auth-str: dongtaiwang.com
    protocol: udp
    sni: apple.com
    up: "11"
    down: "55"
    skip-cert-verify: true
    alpn:
      - h3
  - type: ss
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½
    server: 223.95.183.131
    port: 25819
    cipher: aes-128-gcm
    password: b637f2e47b7827b308ebf399008075d2
  - type: ss
    name: ğŸ‡®ğŸ‡·_IR_ä¼Šæœ—
    server: 217.60.249.112
    port: 443
    cipher: chacha20-ietf-poly1305
    password: 0eC4ZBvStOgQEzTpCYjWN5
  - type: vless
    name: ğŸ‡¯ğŸ‡µ_JP_æ—¥æœ¬
    server: 116.80.44.144
    port: 27724
    uuid: ebd8539d-e249-4a39-8f90-e8585e8cc35e
    network: tcp
    servername: www.yahoo.co.jp
    tls: true
    encryption: none
    reality-opts:
      public-key: rYH4wPTVzSwtpXgI3U7YxppIP6oudD-425vT7pyhj1w
    client-fingerprint: chrome
    flow: xtls-rprx-vision
  - type: ss
    name: ğŸ‡¬ğŸ‡§_GB_è‹±å›½
    server: 82.38.31.214
    port: 8080
    cipher: chacha20-ietf-poly1305
    password: k1dBOmOB4oqi7Ump37a1bQ
  - type: ss
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_1
    server: 223.95.183.131
    port: 39398
    cipher: aes-128-gcm
    password: b637f2e47b7827b308ebf399008075d2
  - type: vless
    name: ğŸ‡µğŸ‡±_PL_æ³¢å…°
    server: 185.136.132.171
    port: 24170
    uuid: fe21e399-ec6f-4cb5-8441-e911178665b1
    network: tcp
    servername: speedtest.net
    tls: true
    encryption: none
    reality-opts:
      public-key: VsmNi1ZMXVOwhCWpbCp51w-D_DzrxWX4jgfpcU0S9G4
      short-id: 2fb2106a629b
      spider-x: /
    client-fingerprint: chrome
  - type: ss
    name: ğŸ‡®ğŸ‡·_IR_ä¼Šæœ—_1
    server: 151.242.251.152
    port: 8080
    cipher: chacha20-ietf-poly1305
    password: k1dBOmOB4oqi7Ump37a1bQ
  - type: vmess
    name: ğŸ‡ºğŸ‡¸ USÂ²_3|0.9MB/s|52%|GPTâº|TK|NF|X|KeepHistory
    server: v29.hdacd.com
    port: 30829
    uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
    alterId: 2
    network: tcp
    cipher: auto
    servername: v29.hdacd.com
  - type: ss
    name: ğŸ‡¦ğŸ‡«_AF_é˜¿å¯Œæ±—
    server: 121.127.46.147
    port: 989
    cipher: aes-256-cfb
    password: f8f7aCzcPKbsF8p3
  - type: ss
    name: ğŸ‡¬ğŸ‡§_GB_è‹±å›½_1
    server: 146.70.61.37
    port: 8080
    cipher: rc4-md5
    password: 14fFPrbezE3HDZzsMOr6
  - type: vmess
    name: ğŸ‡ºğŸ‡¸ USÂ²_5|6.9MB/s|51%|GPTâº|GM|YT|TK|NF|X|KeepHistory
    server: v8.hdacd.com
    port: 30808
    uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
    alterId: 2
    network: tcp
    cipher: auto
    servername: v8.hdacd.com
  - type: ss
    name: ğŸ‡¹ğŸ‡·_TR_åœŸè€³å…¶
    server: 193.135.174.135
    port: 990
    cipher: chacha20-ietf-poly1305
    password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  - type: ss
    name: ğŸ‡µğŸ‡¹_PT_è‘¡è„ç‰™
    server: 185.113.143.186
    port: 990
    cipher: chacha20-ietf-poly1305
    password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  - type: ss
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_2
    server: 223.95.183.131
    port: 47116
    cipher: aes-128-gcm
    password: b637f2e47b7827b308ebf399008075d2
  - type: ss
    name: ğŸ‡²ğŸ‡©_MD_æ‘©å°”å¤šç“¦
    server: 176.123.5.253
    port: 990
    cipher: chacha20-ietf-poly1305
    password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  - type: trojan
    name: ğŸ‡¬ğŸ‡§_GB_è‹±å›½_2
    server: 146.70.90.195
    port: 57452
    password: t1k169n5zmvvwn96r9ft
    network: tcp
    sni: api-yandex.maps.ru
    skip-cert-verify: true
    tls: true
  - type: ss
    name: ğŸ‡«ğŸ‡®_FI_èŠ¬å…°
    server: 95.111.222.113
    port: 443
    cipher: chacha20-ietf-poly1305
    password: SVt6ZiWzRI1Yxeig4xBZwiJOt6ceXwGa
  - type: ss
    name: ğŸ‡®ğŸ‡¹_IT_æ„å¤§åˆ©
    server: 185.213.23.63
    port: 990
    cipher: chacha20-ietf-poly1305
    password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  - type: ss
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½
    server: 173.234.29.2
    port: 990
    cipher: chacha20-ietf-poly1305
    password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  - type: ss
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_1
    server: 38.165.231.25
    port: 990
    cipher: chacha20-ietf-poly1305
    password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_2
    server: ilta-wzxrxkdhbjpnprhkkpplsjwawhssvollvxzdhqshiqckwdgrdm.orbnet.xyz
    port: 443
    uuid: 0e8a6896-ad90-4a3b-89a3-77d64aa409e2
    network: tcp
    servername: i2pd.website
    tls: true
    encryption: none
    reality-opts:
      public-key: YVDo7U4O-AT2fa5H9E7hyYHKgfZd1vB6UdbAf2ggWQE
      short-id: 55e6af1a35e64a98
    client-fingerprint: chrome
    flow: xtls-rprx-vision

