# åˆ›å»ºè€…ï¼šç”¨æˆ·è‡ªå®šä¹‰èŠ‚ç‚¹é…ç½®
# åˆ›å»ºæ—¶é—´ï¼š2025-09-27 08:00:00

# å•èŠ‚ç‚¹é…ç½®
proxies:
  - type: tuic
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½
    server: twtuic01.yydzx.xyz
    port: 15968
    uuid: e715f8e2-664c-4f6e-bb71-56d967cebb96
    password: e715f8e2-664c-4f6e-bb71-56d967cebb96
    sni: twtuic01.yydzx.xyz
    alpn:
      - h3
    congestion-controller: bbr
  - type: tuic
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_1
    server: jptuic01.yydzx.xyz
    port: 14958
    uuid: e715f8e2-664c-4f6e-bb71-56d967cebb96
    password: e715f8e2-664c-4f6e-bb71-56d967cebb96
    sni: jptuic01.yydzx.xyz
    alpn:
      - h3
    congestion-controller: bbr
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½
    server: delilah.ns.cloudflare.com
    port: 443
    uuid: 53f0bca8-f170-4ef7-8031-c7d441189dbf
    network: ws
    servername: 638987378208894304.sentra-amshr.info
    tls: true
    encryption: none
    ws-opts:
      path: /cahttingws
      headers:
        Host: 638987378208894304.sentra-amshr.info
    client-fingerprint: chrome
  - type: trojan
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_2
    server: 116.49.237.130
    port: 4094
    password: BxceQaOe
    network: tcp
    sni: t.me/ripaojiedian
    skip-cert-verify: true
  - type: hysteria2
    name: ğŸ‡¨ğŸ‡¦_CA_åŠ æ‹¿å¤§
    server: 140.238.137.165
    port: 30102
    password: 338ce171-d764-4610-8fd5-6688b0d321f0
    skip-cert-verify: true
    sni: du.wish.ml
  - type: vmess
    name: ğŸ‡®ğŸ‡¹ITÂ²_1|1.6MB/s|TK-NL|X|KeepHistory
    server: v5.heduian.link
    port: 30805
    uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
    alterId: 2
    network: tcp
    cipher: auto
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_1
    server: zula.ir
    port: 2096
    uuid: 97909ffd-6da0-4893-9d63-00e72ad55256
    network: ws
    servername: frAgteSt.JaHANGiRKh.eU.orG
    tls: true
    encryption: none
    ws-opts:
      path: /
      headers:
        Host: frAgteSt.JaHANGiRKh.eU.orG
    client-fingerprint: chrome
  - type: vless
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_3
    server: 62.60.177.167
    port: 443
    uuid: 6670529b-265a-4ee9-b944-bdaee2638ef2
    network: tcp
    servername: st.ozone.ru
    tls: true
    encryption: none
    reality-opts:
      public-key: uI6NV8Mkk7kf864izhLcAnk6nVDH6cE-_5HRJwMQGXs
      short-id: 0ea9a621ae03e231
    client-fingerprint: chrome
    flow: xtls-rprx-vision
  - type: vmess
    name: SEğŸ‡¸ğŸ‡ª | dir.lightnright.com-5228 | 255.21ms
    server: dir.lightnright.com
    port: 5228
    uuid: 6202ab997f570a6a180ae980b41f5789
    alterId: 0
    network: tcp
    cipher: auto
  - type: vless
    name: ğŸ‡©ğŸ‡ª_DE_å¾·å›½
    server: vp9.myphotomoments.ir
    port: 443
    uuid: Warpi-Free-Vpn-In-GooglePlay
    network: tcp
    encryption: none
  - type: trojan
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_2
    server: 104.25.254.4
    port: 2087
    password: d0298536-d670-4045-bbb1-ddd5ea68683e
    network: ws
    sni: azadnet-bdr.pages.dev
    tls: true
    ws-opts:
      path: /azadnet-bdr.pages.dev/?ed=2560&PROT_TYPE=trojan
      headers:
        Host: azadnet-bdr.pages.dev
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_3
    server: ilta-wzxrxkdhbjpnprhkkpplsjwawhssvollvxzdhqshiqckwdgrdm.orbnet.xyz
    port: 443
    uuid: 0e8a6896-ad90-4a3b-89a3-77d64aa409e2
    network: tcp
    servername: i2pd.website
    tls: true
    encryption: none
    reality-opts:
      public-key: YVDo7U4O-AT2fa5H9E7hyYHKgfZd1vB6UdbAf2ggWQE
      short-id: 55e6af1a35e64a98
    client-fingerprint: chrome
    flow: xtls-rprx-vision
  - type: vmess
    name: ğŸ”·ğŸ†”@v2ray_configs_poolğŸ”·
    server: dd.openaccessnode.com
    port: 5228
    uuid: 6202ab99-7f57-0a6a-180a-e980b41f5789
    alterId: 0
    network: tcp
    cipher: auto
  - type: vless
    name: ğŸ‡®ğŸ‡¶_IQ_ä¼Šæ‹‰å…‹
    server: fis.jykvpn.com
    port: 443
    uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
    network: tcp
    servername: cdnjs.com
    tls: true
    encryption: none
    reality-opts:
      public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
      short-id: c2a0b2d60a7fc300
    client-fingerprint: chrome
    flow: xtls-rprx-vision
  - type: vless
    name: ğŸ‡®ğŸ‡ª_IE_çˆ±å°”å…°
    server: 34.254.224.37
    port: 48056
    uuid: d811ecf9-4029-4794-a43e-3611c3575b9e
    network: grpc
    servername: 34.254.224.37
    tls: true
    encryption: none
    grpc-opts:
      grpc-service-name: www.bing.com
    client-fingerprint: chrome
    alpn:
      - h2
      - http/1.1
  - type: hysteria2
    name: ğŸ‡³ğŸ‡±_NL_è·å…°
    server: 132.226.162.10
    port: 30102
    password: 338ce171-d764-4610-8fd5-6688b0d321f0
    skip-cert-verify: true
  - type: vless
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_4
    server: 152.53.84.101
    port: 20579
    uuid: 93cd7e0f-8a81-4076-be8b-6d3bf3f8f810
    network: tcp
    servername: ilovepdf.com
    tls: true
    encryption: none
    reality-opts:
      public-key: mT6lh-gtbEuWk3Zk6XGF_hYvpLwxTyvwtH7F-_fRbxI
      short-id: 89f1da93
    client-fingerprint: chrome
    flow: xtls-rprx-vision
  - type: hysteria2
    name: ğŸ‡ºğŸ‡¸_US_ç¾å›½_5
    server: 40.233.80.237
    port: 30300
    password: 2429bee3-e0c1-47dd-b420-75e6512b184b
    skip-cert-verify: true
    sni: www.bing.com
  - type: trojan
    name: ğŸ‡®ğŸ‡·_IR_ä¼Šæœ—
    server: 151.242.164.127
    port: 3443
    password: c2e3cdc0-bc72-3505-b2a9-ea5ed7bfa23f
    network: tcp
    sni: steampipe.akamaized.net
    skip-cert-verify: true
    tls: true
  - type: vless
    name: ğŸ‡¸ğŸ‡¦_SA_æ²™ç‰¹é˜¿æ‹‰ä¼¯
    server: 77.110.119.225
    port: 443
    uuid: 4819860c-0e62-4804-9c59-967e5c2bed7a
    network: tcp
    servername: st.ozone.ru
    tls: true
    reality-opts:
      public-key: hnec5SxCD6Os-u0FNi_YS5CML1a_oWb0niZJ1mGuFBo
      short-id: 07e904766d29b958
    client-fingerprint: chrome
    flow: xtls-rprx-vision
  - type: vless
    name: ğŸ‡®ğŸ‡¹_IT_æ„å¤§åˆ©
    server: fi.podpiska.vip
    port: 443
    uuid: 5d3bffc3-20f6-41ae-9fe7-bb12a122c3a3
    network: tcp
    servername: uspehudacha.com
    tls: true
    encryption: none
    reality-opts:
      public-key: L-7MZ5IB5uSmLn34BQsBOF8XaDN3B2as4ye-nWkJEzI
      short-id: 4a6c2577ce53af9e
    client-fingerprint: chrome
    flow: xtls-rprx-vision
  - type: vmess
    name: ğŸ‡³ğŸ‡± è·å…° 03
    server: v30.heduian.link
    port: 30830
    uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
    alterId: 2
    network: ws
    cipher: auto
    servername: ocbc.com
    ws-opts:
      path: /oooo
      headers:
        Host: ocbc.com
  - type: vless
    name: ğŸ‡²ğŸ‡©_MD_æ‘©å°”å¤šç“¦
    server: sk3.node.ibst.me
    port: 7079
    uuid: a54c3b5a-5f44-4411-8c1e-7bf52a567d7f
    network: tcp
    encryption: none
  - type: ss
    name: ğŸ‡¨ğŸ‡³_CN_ä¸­å›½_4
    server: 103.149.183.154
    port: 8388
    cipher: chacha20-ietf
    password: asd123456
