# åˆ›å»ºè€…ï¼šç”¨æˆ·è‡ªå®šä¹‰èŠ‚ç‚¹é…ç½®
# åˆ›å»ºæ—¶é—´ï¼š2025-09-27 08:00:00

# å•èŠ‚ç‚¹é…ç½®
proxies:
- name: "ðŸ‡ºðŸ‡¸_US_ç¾Žå›½"
  type: "trojan"
  server: "uk-03.allhubb.info"
  port: 8443
  password: "1ce1df7962f71c6f"
  network: "tcp"
- name: "ðŸ‡©ðŸ‡ª_DE_å¾·å›½"
  type: "ss"
  server: "46.183.184.60"
  port: 989
  cipher: "aes-256-cfb"
  password: "f8f7aCzcPKbsF8p3"
- name: "ðŸ‡¨ðŸ‡³_CN_ä¸­å›½->ðŸ‡ºðŸ‡¸_US_ç¾Žå›½"
  type: "vmess"
  server: "v29.heduian.link"
  port: 30829
  sni: ""
  uuid: "cbb3f877-d1fb-344c-87a9-d153bffd5484"
  cipher: "auto"
  network: "ws"
  skip-cert-verify: true
  ws-opts:
    path: "/oooo"
    headers:
      host: "v29.heduian.link"
  alterId: 2
- name: "ðŸ‡¸ðŸ‡ª_SE_ç‘žå…¸"
  type: "ss"
  server: "192.71.166.100"
  port: 989
  cipher: "aes-256-cfb"
  password: "f8f7aCzcPKbsF8p3"
- name: "ðŸ‡¬ðŸ‡§_GB_è‹±å›½_1"
  type: "ss"
  server: "62.100.205.48"
  port: 989
  cipher: "aes-256-cfb"
  password: "f8f7aCzcPKbsF8p3"
- name: "ðŸ‡¬ðŸ‡§_GB_è‹±å›½_2"
  type: "ssr"
  server: "62.100.205.48"
  port: 989
  cipher: "aes-256-cfb"
  password: "f8f7aCzcPKbsF8p3"
  obfs: "plain"
  protocol: "origin"
- name: "ðŸ‡°ðŸ‡·_KR_éŸ©å›½"
  type: "ss"
  server: "154.223.16.212"
  port: 989
  cipher: "aes-256-cfb"
  password: "f8f7aCzcPKbsF8p3"
